### ISSUE TITLE
Console from developer tool is showing an ERR_INVALID_URL for a GET data:image/gif when opening contextual palette

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1023]
### Describe the Bug

error in logs, do not know what is the impact in the end user

### Steps to Reproduce the Bug or Issue

-  Click on teh + button to show the contextual palette

### Screenshots or Videos

![contextualPaletteError](https://user-images.githubusercontent.com/1105127/207610786-1b7adccf-3571-4f43-bda0-b3b00a71dd2d.gif)

### Platform

- OS: Linux
- Browser: Chrome and VS Code
- Version: 0.5.0 and commit c4953a6f3f9b53712d32372dcfbe3b9b7c26e0b2

**Comment by lordrip** [comment]
After a quick check, I see that it only happens for Google Chrome, using Firefox is not reproducible.

On the other hand, it seems that the URI blob it's missing the encoding (`base64`), I've added it, and using an online base64 image parser, I've obtained the following image:

![wrong base64 icon](https://user-images.githubusercontent.com/16512618/208509649-8bf494de-baba-42c8-8c1b-32080b60c7f7.gif)

Is not yet clear to me where is this icon being in use, I assume that it's coming from the dropdown itself, but I haven't found it using Firefox.

I'll provide more information as soon as I get more :smiley:

**Comment by lordrip** [comment]
Update: the missing icon is the `rollback` one

This is how it looks in `Firefox`
![image](https://user-images.githubusercontent.com/16512618/208513445-42479c50-6ac8-4ad6-a043-f2e1ae87a806.png)

This is how it looks in `Google Chrome`
![image](https://user-images.githubusercontent.com/16512618/208513632-4c74e641-6e34-43a6-911a-7167f371c8c0.png)

**Comment by lordrip** [comment]
Hi @Delawen, I see that the steps are coming from the backend, notice how the first `step` has an encoding declared, but the next one (`rollback`) hasn't.

First one:
```json
{
  ...
  "icon": "data:image/png;base64,iVBORw0KG..."
  ...
},
{
  ...
 "icon": "data:image/gif;R0lGODlhUg..."
  ...
}
```

![image](https://user-images.githubusercontent.com/16512618/208522009-ab8bc06e-5e83-4c62-8aee-9996191d95fb.png)

If I'm not mistaken, I think that the endpoint [is defined here](https://github.com/KaotoIO/kaoto-backend/blob/29cf14e10a9e8c4914759c57030e0841f04d6307/api/src/main/java/io/kaoto/backend/api/resource/v1/StepResource.java#L89-L96), but I haven't found where are we declaring the catalog to check whether the icon is wrong there or somewhere else, could you point it out where the catalog information comes from?

**Comment by lordrip** [comment]
I think that now I get it, we're referencing the raw branch `zip` file in [this file](https://github.com/KaotoIO/kaoto-backend/blob/29cf14e10a9e8c4914759c57030e0841f04d6307/api/src/main/resources/application.yaml#L7), I tried updating it locally to reference my pull request and now we can see the icon being displayed correctly
![image](https://user-images.githubusercontent.com/16512618/208541833-5f792139-6ed7-4868-8aef-6a41eed3faf7.png)

**Comment by kahboom** [comment]
@Delawen in case you didn't see it
