### ISSUE TITLE
Persist Opened/Closed Editor

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#105]
As a user, I would like to have the ability to decide whether the code editor is visible. This should persist even when refreshing the page.

Right now if you close the editor and refresh the page, the editor reappears (`src/components/YAMLEditor.tsx`). We should persist these changes to `localStorage` or similar.

**Comment by joshiraez** [comment]
I will work on this if it's open

**Comment by kahboom** [comment]
@joshiraez as we discussed earlier today, let's put this issue on hold for now since we will likely be making changes to the layout soon.

**Comment by kahboom** [comment]
Closing due to new layout & eventually we will be persisting steps on refresh which should be sufficient. Will reopen if we get a request for this feature.
