### ISSUE TITLE
Upgrade to Jest v29.x

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1072]
## Description
We are currently on Jest v27 and need to upgrade to Jest v29. There are some breaking changes, so it might be easier to upgrade first from v27 to v28, and then from v28 to v29.

## Steps
- [Upgrade Jest from v27 to v28](https://jestjs.io/docs/28.x/upgrading-to-jest28)
- [Upgrade Jest from v28 to v29](https://jestjs.io/docs/upgrading-to-jest29)

## Notes
There were about 8 breaking tests from v27 -> v29 ([in this dependabot PR](https://github.com/KaotoIO/kaoto-ui/pull/994)), I was able to fix about 7 of them, but for the last breaking test there was an issue with the Catalog tests I couldn't fix, and I also had other issues with pushing my commits to the dependabot PR. But here's what I did to fix those 7 tests:

1. Add polyfills necessary to get rid of `TextEncoder` error
  a. Add `@inrupt/jest-jsdom-polyfills` to `package.json` as a `devDependency`
  b. In `setupTests.ts` add `import '@inrupt/jest-jsdom-polyfills'`
2. Update `jest-environment-jsdom` version in `package.json` to `29.3.1`, to match the Jest version

**Comment by lordrip** [comment]
@kahboom Sorry for not checking this beforehand, I was looking at #973 and I noticed a few warning logs while executing test and I've put together this [pull request](https://github.com/KaotoIO/kaoto-ui/pull/1077) #1077 :sweat_smile:

@mmelko Please feel free to close my pull request if you have another solution in mind :bow:

**Comment by kahboom** [comment]
Resolved with https://github.com/KaotoIO/kaoto-ui/pull/1077
