### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by skin27** [KaotoIO/kaoto-ui#1076]
I created a simple integration (see simple_integration.txt). After I finished I deployed the integration, but the integration fails to run. From the GUI it's not sure what's happening. 

**To Reproduce**
1. Go to the main page
2. Import the yaml (simple_integration.txt)
       the extensions is .txt by the way, because GitHub won't let me upload yaml files.
4. Click on 'deploy.'
5. The console:

Error processing deployment: Operation: [list]  for kind: [Pod]  with name: [null]  in namespace: [default]  failed.

**Expected behavior**
I would expect some feedback why the error occurs and what to do to prevent it. Is it not possible yet, or do I need to configure some link to Kubernetes?

**Logs**
See attached files

**Environment (please complete the following information):**
 - OS: [e.g. "Windows 10, running in Docker"]
 - Kaoto Version [0.5]

**Additional context**

Attached FiIes

[simple_integration.log](https://github.com/KaotoIO/kaoto-backend/files/10187189/simple_integration.log)
[simple_integration.txt](https://github.com/KaotoIO/kaoto-backend/files/10187190/simple_integration.txt)

**Comment by kahboom** [comment]
Closing since we have another issue open for this and are now pointing to this issue for more context.
