### ISSUE TITLE
Duplicate x button in search field

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1097]
### Describe the Bug

There is a duplicate clear button in the search field of the [Catalog](https://github.com/KaotoIO/kaoto-ui/blob/main/src/components/Catalog.tsx). There should only be one.

### Steps to Reproduce the Bug or Issue

1. Open Kaoto
2. Click on the Catalog button
3. Type into the search field
4. See the duplicate x button

### Screenshots or Videos

![x-button](https://user-images.githubusercontent.com/3844502/212371410-3afe39ec-88a7-4a35-838b-1b78d0b7afeb.png)

### Platform

- OS: macOS
- Browser: Chrome
- Version: v0.5.0

**Comment by lordrip** [comment]
Curious enough, the behavior is different on Firefox.

Notice how the `X` from the `Input` is not displayed apart from the row collapsing differently.

![image](https://user-images.githubusercontent.com/16512618/217586925-4f422e6d-88b8-4cb9-bd89-0545da60ff3c.png)

**Comment by lordrip** [comment]
It seems that it is the default behavior for Google Chrome and Internet Explorer
https://developer.mozilla.org/en-US/docs/Web/CSS/appearance#syntax

**Comment by kahboom** [comment]
Interesting, I wonder if we should disable it for Chrome & IE then, although I don't like the idea of disabling a native behavior. I do wonder why this isn't already addressed in PatternFly. 🤔  One other thing is that the row shouldn't collapse that way in Firefox, maybe we should open an issue for that and set up Chromatic for Storybook now that we have it (time-permitting 😅 ).

**Comment by lordrip** [comment]
Personally, I don't like the idea of disabling native behavior either :sweat_smile:,  but probably in this case we could make a tiny exception given that @patternfly already provides one.

I prepared a pull request #1239 to see the difference between the Before / After to make an informed decision :)

**Comment by lordrip** [comment]
For the Mozilla Firefox issue, I created this issue #1245
