### ISSUE TITLE
Re-enable e2e tests

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1099]
### Please describe the task that needs to be done

Now that the main issues with the code editor have been resolved, we should be able to add back e2e tests.

- [x] Create common happy paths
- [x] Update existing e2e tests
- [x] Add any missing e2e tests
- [x] Update relevant API keys where necessary
- [x] Ensure e2e tests are run on each PR

Tests should only be run against the `main` branch, not for forks. Relates to #1100.

**Comment by kahboom** [comment]
@tplevko no worries I will take a look, thank you for all of your help with this!

**Comment by tplevko** [comment]
@kahboom closing this as the e2e tests are already reenabled on PR's. Thanks for helping out with this.
