### ISSUE TITLE
Re-enable Storybook

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1100]
### Please describe the task that needs to be done

We should look to re-enable Storybook to continue to ensure that our code base has the separation of concerns for visual components.

- [x] Re-add Storybook
- [x] Fix Storybook (again) after class implementation, unless #1233 gets resolved beforehand
- [x] Add MSW to mock network requests where necessary (see #1258, hopefully we can use this mocking for both types of tests)
- [x] Add stories for components
- [x] Add documentation for components, where possible
- [x] Update relevant API keys where necessary
- [x] Ensure Storybook stories are run on each PR
- ~~Test the stories, whether through React Testing Library or Cypress component testing~~ TBD, might add too much overhead

Tests should only be run against the `main` branch and primary repo, not for forks. This could be good to do once #1183 and other refactoring of stateful components is done.

**Comment by kahboom** [comment]
@igarashitm - Originally I wanted to wait to have this once we refactored the UI components into stateless components, but I think it would be good to already start building them again and creating basic stories and docs for the components like this: https://storybook.js.org/addons/@storybook/addon-docs

What do you think? Or wait until the refactor (depending what kind of refactoring you decide to do)? I wouldn't start on this right away but at the end of next week if I finished visual branching and e2e tests in time.

**Comment by igarashitm** [comment]
definitely +1, storybook is worth paying the cost to maintain, useful for design discussion as well as for detecting visual regression earlier IMO.

**Comment by igarashitm** [comment]
In theory internal refactoring shouldn't conflict with storybook work - maybe little bit in mock data, but should be manageable.
