### ISSUE TITLE
Incorrect form input indication for number inputs

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-ui#1155]
### Please describe the feature that you want to propose

The Kamelet forms provide - based on the properties types - text and number inputs. The number input should indicate if the provided input is not a number.
![Screenshot from 2023-01-24 10-34-13](https://user-images.githubusercontent.com/4180208/214257745-62afcc76-c720-436f-8687-6efef55f47f3.png)

**Comment by Delawen** [comment]
This will be solved in https://github.com/KaotoIO/kaoto-ui/issues/1366

**Comment by Delawen** [comment]
This issue is just a specific use case of the bigger problem: no placeholders/variables on non-text fields
