### ISSUE TITLE
Spinner in config should increment by 1 instead of 0.01

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1201]
### Please describe the feature that you want to propose

In most cases, the values are integer and not decimals

![spinnerIssue](https://user-images.githubusercontent.com/1105127/216106051-68c53136-20fc-4597-bc52-203f77cf9f08.gif)

**Comment by tplevko** [comment]
should be doable once there is new `uniforms-patternfly` build with this included - https://github.com/kiegroup/kie-tools/pull/1579
