### ISSUE TITLE
Steps catalog search bar split into 2 lines in Mozilla Firefox

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-ui#1245]
### Describe the Bug

There's an inconsistent behavior between Google Chrome and Mozilla Firefox in regard to the Steps catalog search bar that causes the search bar to be split into two lines

This happens when searching for a step.

#### Mozilla Firefox - no search
![Screenshot from 2023-02-13 10-36-50](https://user-images.githubusercontent.com/16512618/218423493-92fa18d3-2d44-471d-8899-3f10a36e06fb.png)

#### Mozilla Firefox - search
![Screenshot from 2023-02-13 10-36-58](https://user-images.githubusercontent.com/16512618/218423499-5d8aaec0-6dd1-4efc-b004-d078bbafbdb8.png)

#### Google Chome - no search
![Screenshot from 2023-02-13 10-35-55](https://user-images.githubusercontent.com/16512618/218423481-6ea47c33-d557-4ee0-b358-4b810668e42f.png)

#### Google Chome - search
![Screenshot from 2023-02-13 10-36-13](https://user-images.githubusercontent.com/16512618/218423485-59da35cf-270b-4e99-b0f3-55c0c6cb3f69.png)

### Steps to Reproduce the Bug or Issue

1. Open the steps catalog
2. Write a letter to start searching
3. Notice how the input field gets wider in Chrome or the search bar is split in Firefox

### Platform

- OS: [Linux]
- Browser: [Chrome, Firefox]
- Version: [0.6.2-dev]

**Comment by tplevko** [comment]
@lordrip done in https://github.com/KaotoIO/kaoto-ui/pull/1950

can we close this?

**Comment by lordrip** [comment]
Sure thing, I linked the pull request with the issue and we're good to go :muscle:
