### ISSUE TITLE
Add more context to mini-catalog calls.

### ISSUE THREAD

**Issue by Delawen** [KaotoIO/kaoto-ui#1246]
### Please describe the feature that you want to propose

When the mini-catalog opens, there is a call to the backend api like `http://....../api/v1/steps?dsl=KameletBinding&type=MIDDLE,END&namespace=default`

For https://github.com/KaotoIO/kaoto-backend/issues/224 I would like to have a bit more context. I would like to have the `id` of the previous and the following (if exists) steps to return a more accurate list of available steps.

I am going to add to the backend two more parameters to this endpoint https://kaotoio.github.io/kaoto-backend/api/index.html#api-StepResource-v1StepsGet

`previous-step` that should contain the `id` of the step immediately before the `+` button that opens the mini-catalog. If this is the first step of a branch, add the previous step too, the one that branches.
`following-step` that should contain the `id` of the step right after the `+` button, if such a step exists. If not, don't send it.

**Comment by mmelko** [comment]
I can but I can see this as post release thing ?

**Comment by Delawen** [comment]
Yes, this is after 1.0.0

**Comment by Delawen** [comment]
This will be needed for https://github.com/KaotoIO/kaoto-backend/issues/224
