### ISSUE TITLE
Append to step with branches appending step at the end of the integration instead of after the step.

### ISSUE THREAD

**Issue by mmelko** [KaotoIO/kaoto-ui#1253]
### Describe the Bug

Append to step with branches appending step at the end of the integration instead of after the step. See:
![Kapture 2023-02-14 at 11 46 39](https://user-images.githubusercontent.com/6814482/218713984-f600a089-712a-473e-99d4-627a7b1e034c.gif)
Aws step should be added before zookeeper and not after. 

### Steps to Reproduce the Bug or Issue

See the gif.

### Platform

Chrome

**Comment by kahboom** [comment]
Well, we might not have to fix this bug if we implement https://github.com/KaotoIO/kaoto-ui/issues/1263

**Comment by kahboom** [comment]
fixed via https://github.com/KaotoIO/kaoto-ui/pull/1278
