### ISSUE TITLE
All modals are now huge

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1254]
### Please describe the task that needs to be done
If you try to delete the integration, this is what the confirmation modal looks like:

![Screen Shot 2023-02-14 at 1 57 41 pm](https://user-images.githubusercontent.com/3844502/218759391-633940fc-7574-4db4-b320-d9ad41fafe73.png)

## Steps to Reproduce
1. Click on the dropdown settings from the top right-hand corner
2. Click `Delete`
3. See the huge modal

The same happens with the `AppearanceModal` and `SettingsModal`.

## Suggested Change
We should change this to a smaller modal (relevant docs from PatternFly here: https://patternfly-react.surge.sh/components/modal). The component are called `ConfirmationModal`, `SettingsModal`, and `AppearanceModal` (but please check that I didn't miss any).

**Comment by lhein** [comment]
The same issue occurs with all the settings dialogs (like dark / light theme and the select the integration type).

**Comment by kahboom** [comment]
Yeah I think this is a regression after updating PF at some point.
