### ISSUE TITLE
Visualization: Add a Step placeholder should have label background

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1256]
### Describe the Bug

For consistency, the "ADD A STEP" placeholder should have a label background color, like the rest of the steps.

### Suggested Solution
To fix this we would need to check the `stepNode__Label` CSS class referenced within the `VisualizationStep.tsx` component. You will find "normal" steps using this class, and the placeholder step further down in the component likely doesn't, but please check.

### Steps to Reproduce the Bug or Issue

1. Just open Kaoto
2. See `ADD A STEP` placeholder

### Screenshots or Videos

![Screen Shot 2023-02-14 at 2 03 04 pm copy](https://user-images.githubusercontent.com/3844502/218765728-b5233f65-ba74-4d3f-a982-f4ac2323c3e5.png)

### Platform

- OS: macOS
- Browser: Chrome
- Version: `0.6.2-dev`

**Comment by mmuzikar** [comment]
Looks like this is no longer an issue on the main branch. The background is applied on both firefox and chromium.
![image](https://user-images.githubusercontent.com/46345469/236409812-aba2eb18-3694-4f7e-8e52-0a848a55d25f.png)

**Comment by lordrip** [comment]
Hi @mmuzikar , thanks for checking this out:

I think that you're right, looking into the [stable build](red.ht/kaoto) it still happens
![image](https://user-images.githubusercontent.com/16512618/236441010-d0a6f4e9-a7cf-4f58-981f-ee9e7dd30b30.png)

but checking the [nightly build](https://nightly-kaoto-unstable.mariasde-cluster-c22fc5e8e66e9470d8f58db21c47bfd0-0000.eu-de.containers.appdomain.cloud/) it's fixed
![image](https://user-images.githubusercontent.com/16512618/236441115-994bc7e1-9ea0-414b-8652-ab210d6318f2.png)

I'll close this issue then, thanks again for investigating 💪
