### ISSUE TITLE
Catalog: Mini catalog is taking a long time to load

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1269]
### Describe the Bug

Mini catalog is taking a long time to load, which affects the UX.

### Steps to Reproduce the Bug or Issue

1. Open Kaoto
2. Click on `ADD A STEP` placeholder
3. Mini catalog opens
4. Steps are loaded but very slowly

### Screenshots or Videos

TBD

### Platform

- OS: macOS, Linux
- Browser: Chrome, Safari, Firefox
- Version: `0.6.2-dev`

**Comment by igarashitm** [comment]
OK I stopped here just because this is the top among unassigned bugs - do we want to retrieve step catalog only once on initialization and cache it at UI side? any other option?

**Comment by igarashitm** [comment]
Found that `Catalog.tsx` is caching until DSL type is changed, do we just want to do the same for mini catalog?
https://github.com/KaotoIO/kaoto-ui/blob/c1aff24a9c1facd7282b852ea059868c4bbe046e/src/components/Catalog.tsx#L46

**Comment by igarashitm** [comment]
It would be nice if it could do background loading hooked on initialization and DSL type change, but that would need a deeper surgery I guess?
