### ISSUE TITLE
Labels of CBR to branches connection get lost

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-ui#1279]
### Describe the Bug

When creating a CBR and adding 2 when and 1 otherwise branch the otherwise label is visible for the connection to the otherwise branch. When you then set the simple condition for the 2 other branches and start to populate the branches with steps the otherwise label will disappear and it is not clear what makes the conditions for the other branches causing it to show up on the connection or not. I fear it will only be displayed if the length of the condition fits the width of the connection line but it is not always displayed.

### Steps to Reproduce the Bug or Issue

1. set camel route type
2. choose a source of your choice
3. add a choice next to it
4. add 2 Whens and 1 otherwise via step extension
5. fill the conditions of the 2 when nodes
6. start populating the whens and the otherwise with at least 2 steps and monitor what happens to the connection labels

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lhein** [comment]
Happy to provide a screenshot:
![grafik](https://user-images.githubusercontent.com/435853/219699973-ea88184e-4150-45c9-a4c3-fba1a89f73c2.png)

**Comment by Delawen** [comment]
@lhein Are you using the choice extension to configure those branches?

The label is the condition for each branch. So if you don't add the condition, the label is empty.

![image](https://user-images.githubusercontent.com/726590/220332492-04b700bd-9b0a-44c1-bc65-2d75d5a853c0.png)

**Comment by Delawen** [comment]
Oh wait, I see, when adding the steps the label is gone. Forget I said anything!

**Comment by igarashitm** [comment]
Yes kaoto-ui always passes edge labels, but React Flow doesn't show it when edge type is `delete`

**Comment by igarashitm** [comment]
OK, Custom Edge has to put the label manually - https://reactflow.dev/docs/examples/edges/custom-edge/
