### ISSUE TITLE
UX: Show active/inactive toolbar icons

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1283]
### Please describe the task that needs to be done

A very tiny nitpick, but it'd be nice if we highlighted which component was open by showing active/inactive toolbar icons. For example, if the code editor is open, the icon for it in the toolbar should look different to the others.

The component to look at for this issue is `KaotoToolbar`.

![Screen Shot 2023-02-17 at 5 10 19 pm](https://user-images.githubusercontent.com/3844502/219719008-d0b088ed-a38b-4151-8794-67b52132ff74.png)

**Comment by pnaik1** [comment]
Hello Rachel , I wanted to take this issue , can I do so?

**Comment by lhein** [comment]
Contributions are always welccome ;)

**Comment by pnaik1** [comment]
Okay , Thank you
