### ISSUE TITLE
Display the selected integration type in a prominent position on screen

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-ui#1296]
### Please describe the feature that you want to propose

At the moment the integration type is buried in the settings of Kaoto and is not visible right away. How about displaying the currently selected type in a prominent position like the top menu bar so it is always visible? We should make it even a drop down so people can easily select a different type when starting a new integration in Kaoto.

**Comment by kahboom** [comment]
@lhein how often do you see users wanted to change between DSLs though?

**Comment by lhein** [comment]
I am doing that every time I open it on operateFirst just to switch to Camel Routes type. So either we ask the user for the type when opening the canvas or we let them select it easily I'd say.

**Comment by kahboom** [comment]
If we go with the first option then this issue probably won't be needed, I think it'd be more related to #226. Ideally, the toolbar will be as clean as possible with only things the user will want to access frequently, so I'm not sure I'm a fan of the second option, but we can check with UX.
