### ISSUE TITLE
Mandatory fields in the step's config panel

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-ui#1301]
### Please describe the feature that you want to propose

Some fields are mandatory in the configuration panel of a step. These are marked with a * but atm they are not easy to spot if the step has a lot of configuration options (for instance activemq or kafka components). 

How about showing them in a separate tab or alternatively at the top of the configuration page (maybe grouped as 'Mandatory')?

relates also to KaotoIO/kaoto-backend#474

**Comment by kahboom** [comment]
Required fields should only be indicated next to the field itself, I've never really seen it any other way on a UI (personally I'd find it a bit confusing if it were grouped elsewhere). We can ask UX though.

If you wanted them to show more prominently with a red marking or something, that would be different as it enhances the existing functionality. There has been more discussion about default values and required fields here: https://github.com/KaotoIO/kaoto-ui/pull/1216

**Comment by lhein** [comment]
I would at least make the label appear bold.

**Comment by rstroop** [comment]
I agree that mandatory fields should be at the top. In fact, I would hide other fields under an advanced tab like UI forms already do in OpenShift. The experience for the Kafka component for example requires me to scroll down multiple pages to find the Topic name I want to connect to, when that should be front and center for the user. Less clicks, less scrolling.

**Comment by lordrip** [comment]
Here's another example but now with `debezium-mongodb`
![image](https://user-images.githubusercontent.com/16512618/226674508-40eb1c30-cd08-48fe-9dcf-2450501c01c8.png)

**Comment by kahboom** [comment]
@rstroop :
>In fact, I would hide other fields under an advanced tab like UI forms already do in OpenShift. 

@lhein :
>Yep, we had something similar in the old tooling.
>Details tab vs. Advanced tab

What I find confusing about that approach is that optional fields are not always = advanced fields, but if that's how they do it in the old tooling and in OpenShift and that's what users are used to, then I guess it's worth considering a similar pattern.

**Comment by lordrip** [comment]
This is another test using the following approach:
1. Move mandatory parameters to the top
2. Sort alphabetically the rest of the parameters

### `activeMQ`
![image](https://user-images.githubusercontent.com/16512618/226679660-d4c84c3d-d3b1-4416-9d0d-fa4fde759f35.png)

### `debezium-mongodb`
![image](https://user-images.githubusercontent.com/16512618/226679995-41f3352a-7e77-4eaf-8424-b62bbe624d0f.png)

**Comment by lordrip** [comment]
Alrighty, `sort-parameters` take 3

1. Move mandatory parameters to the top
2. Sort them alphabetically
3. Sort alphabetically the rest of the parameters

### debezium-mongodb
![image](https://user-images.githubusercontent.com/16512618/226684511-761fc889-35a4-4f1f-a000-823d24161c89.png)

**Comment by rstroop** [comment]
I like the mandatory fields at the top. I do not like the alphabetized versions at all, and don't see that as a requested suggestion anywhere. I would group all of the excess fields in an advanced tab or at least add a space between the mandatory fields and others as it all still blurs together and makes it harder to see what I need to actually fill in to make the component work.

**Comment by lhein** [comment]
We discussed that change in the team and sorting it alphabetically makes sense to me because if you look for a specific parameter you have an easier time locating it. The grouping issue is a separate one and will not be tackled as part of this issue.

**Comment by rstroop** [comment]
Most of the time I'm not looking for a specific field. Normally I'm just trying to add the mandatory fields and then when I need to configure something, it's often a group of things like security parameters which don't always start with the same letter. The goal should be to put the things people change often together and near the top so there is less scrolling. That can take place as part of a separate effort, but most of the time the configuration parameters are already grouped together in the default order. You just need to move the mandatory fields and the other fields stay near their related options.

**Comment by lhein** [comment]
I am not convinced that this was the case before this change. Just have a look at the screenshot in the linked issue above...it looks quite wild and random.

**Comment by rstroop** [comment]
We should sort things the same way Camel does. Here is the link to the docs page for the ActiveMQ component from the first image: https://camel.apache.org/components/3.20.x/activemq-component.html

You are correct that the order Kaoto has is wrong and seemingly random. Camel groups properties by type and that information should be available to Kaoto in the schema for the component. The types are common, consumer, consumer(advanced), producer, producer (advanced), advanced, filter, logging, security, transaction, transaction (advanced). Within those groups, everything is alphabetized as it should be. But if you just alphabetize everything without the groups it gets messy.

Hopefully we can pull those groupings right out of the docs without any extra effort and keep them under expandable tabs so as not to clutter the screen with 100 properties. We also don't want to add our own metadata around sorting, we should use what's already in Camel until we have AI sorting it for us.

**Comment by lhein** [comment]
Would you mind putting your comments on [#](https://github.com/KaotoIO/kaoto-backend/issues/474) instead? This issue will be closed soon and we risk losing the info.

**Comment by lordrip** [comment]
After checking both opinions, it will be nice to have the group information, but unfortunately we don't have it just yet from the backend response.

That being said, should I move forward with the alphabetical order? I'm happy either way, I can also keep the order and then if it's confusing, we can just remove that bit through a minor release.
