### ISSUE TITLE
Step extension `do-try` is not working

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1354]
### Describe the Bug

config panel for do-try is not working

### Steps to Reproduce the Bug or Issue

1. add a step
2. add a do-try
3. select do-try
4. Thje config panel has an error

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/1105127/222661806-6a70c993-70c3-471b-bd35-a6ad8960bc77.png)

error in console log:

```
error { target: script, isTrusted: true, srcElement: script, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 166100318, … }
​
bubbles: false
​
cancelBubble: false
​
cancelable: false
​
composed: false
​
currentTarget: null
​
defaultPrevented: false
​
eventPhase: 0
​
explicitOriginalTarget: <script src="https://kaotoio.github.i…catch-eip/remoteEntry.js" type="text/javascript" async="">
​
isTrusted: true
​
originalTarget: <script src="https://kaotoio.github.i…catch-eip/remoteEntry.js" type="text/javascript" async="">
​
returnValue: true
​
srcElement: <script src="https://kaotoio.github.i…catch-eip/remoteEntry.js" type="text/javascript" async="">
​
target: <script src="https://kaotoio.github.i…catch-eip/remoteEntry.js" type="text/javascript" async="">
​
timeStamp: 166100318
​
type: "error"
​
<get isTrusted()>: function isTrusted()
​
<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … }
react-dom.production.min.js:189:21
```

### Platform

OperateFirst

**Comment by apupier** [comment]
the mentioned link https://kaotoio.github.io/try-catch-eip/remoteEntry.js is leading to a 404

**Comment by mmelko** [comment]
https://github.com/KaotoIO/kaoto-viewdefinition-catalog/pull/19

**Comment by mmelko** [comment]
PR: https://github.com/KaotoIO/kaoto-backend/pull/500

**Comment by apupier** [comment]
this is still not working.

The error is no mor eon Ui side, there is now a stacktrace on Kaoto backend:

```

**Comment by lordrip** [comment]
Related pull request to `view-definition.zip` file to include the previous pull request changes
https://github.com/KaotoIO/kaoto-backend/pull/517

**Comment by lordrip** [comment]
Also added another pull request to reword a couple of sentences
https://github.com/KaotoIO/step-extension-repository/pull/207
