### ISSUE TITLE
Config panel for `unmarshal` and `marshal` are not working - `Field not found in schema: "properties.$"`

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1355]
### Describe the Bug

Step extension `unmarshal` is not working. There is the message in config panel `Field not found in schema: "properties.$"`

### Steps to Reproduce the Bug or Issue

1. add a step
2. add unmarshal element
3. select unmarshal
4. See config tab

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/1105127/222664552-40e5f33c-94ea-42e3-b06f-f729a638bf34.png)

in console log:
```
Invariant Violation: Field not found in schema: "properties.$"
    invariant browser.js:38
    fieldInvariant JSONSchemaBridge.js:11
    getField JSONSchemaBridge.js:109
    getField JSONSchemaBridge.js:96
    getField 8.js:2357
    memoized Lodash
    useField useField.js:24
    Field connectField.js:35
    React 13
    setState vanilla.mjs:9
    setState vanilla.mjs:9
    setHoverStepUuid 8.js:849
    onMouseLeave 8.js:3550
    React 11
react-dom.production.min.js:189:21
```

### Platform

OperateFirst

**Comment by mmelko** [comment]
Root cause of this is actually with our current schema generation for autofields. One of the fix would be creating separate step extension to override it or ignore array fields for the details views and leave it configurable only from the codeeditor. WDYT ? @apupier @kahboom

**Comment by apupier** [comment]
To mitigate the issue, I think we can display the field like other types that are not supported. And create an enhancement to support array fields in generated form.
For the step extension, it depends if this field of `unmarshal ` is very commonly used or not and if it is simpler than implementing the support of array fields in generated form.

**Comment by mmelko** [comment]
So I've look into the camel-yaml-dsl .. and it looks like there isn't any list properties only a dataformat. But every dataformat can have different properties so this looks like an adept for a step extension.

**Comment by mmelko** [comment]
I've created  #1405 to mitigate this and possibly with other steps and https://github.com/KaotoIO/kaoto-backend/issues/515.
