### ISSUE TITLE
`e.endpoint is undefined` in config panel for http-source when uploading an open api spec

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1359]
### Describe the Bug

![image](https://user-images.githubusercontent.com/1105127/222667977-f6f4b3cd-1676-4fdf-a083-2029d1b2d997.png)

### Steps to Reproduce the Bug or Issue

1. Create a KameletBinding
2. add an http-source
3. select http-source
4. go to Extented configuration
5. paste https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/api-with-examples.yaml  in field for open api spec and click load
6. mess age something went wrong with e.endpoint is undefined is displayed

### Platform

OperateFirst

**Comment by igarashitm** [comment]
It didn't reproduce for me but hit another issue #1416
