### ISSUE TITLE
Deleting a step with the Details panel open don't close it automatically

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-ui#1360]
### Describe the Bug

If the step details panel is open, deleting the selected step closes it. This is not the case for the first step, which remains with an empty step details panel.

### Steps to Reproduce the Bug or Issue

1. Start with an empty canvas
![image](https://user-images.githubusercontent.com/16512618/222672898-0d33992d-839a-4cd4-b6a0-185ae9b17857.png)

2. Add any step, for instance, `timer`
![image](https://user-images.githubusercontent.com/16512618/222672984-1ec8b2d3-0614-4dff-b04a-10f235839011.png)

3. Click on the step to open the step details panel.
![image](https://user-images.githubusercontent.com/16512618/222673162-8a130a2b-ba19-4b83-8d1b-546830cdab8d.png)

4. Delete the step while the side panel it's open
![image](https://user-images.githubusercontent.com/16512618/222673284-1d6a2976-c570-4cd2-ae12-8833df219b48.png)

5. Now the step it's deleted but the step details panel it's still open and empty
![image](https://user-images.githubusercontent.com/16512618/222673507-0a912516-3d20-4b74-a20c-9bee8881a5a2.png)

### Screenshots or Videos

[Screencast from 2023-03-03 09-43-47.webm](https://user-images.githubusercontent.com/16512618/222673757-b77e5a29-09bb-421e-889b-c8b34c3b4cc0.webm)

### Platform

- OS: [Linux]
- Browser: [Firefox]
- Version: [0.7.1-dev]

**Comment by mmuzikar** [comment]
I'm taking a look at this
