### ISSUE TITLE
Step details aren't always fetched when inserting the step

### ISSUE THREAD

**Issue by mmelko** [KaotoIO/kaoto-ui#1370]
### Describe the Bug

When inserting the step between two steps, details aren't fetched. 

![Screenshot 2023-03-03 at 10 57 31](https://user-images.githubusercontent.com/6814482/222690340-06e9fd9b-c2f0-4a2c-b2b6-c7b7c6efb985.png)

### Steps to Reproduce the Bug or Issue

1.select some step (e.g activemq)
2.add another step (eg.activemq again)
3. insert step in between (aggregade or activemq)

### Platform

everywhere

**Comment by kahboom** [comment]
Do you mean after you insert a step and then click on the newly inserted step?

**Comment by kahboom** [comment]
Nevermind just saw #1369 is a duplicate, but that one is clearer
