### ISSUE TITLE
Make edge arrows bigger and more visible

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1382]
### Please describe the feature that you want to propose

Make the arrow in the visualization bigger:

![Screen Shot 2023-03-03 at 2 17 05 pm](https://user-images.githubusercontent.com/3844502/222745251-c72600e6-4bc2-4e6d-a8cd-b81b762660c7.png)

There isn't really a way to do this from the settings for React Flow, so it will probably have to be done through custom CSS.

**Comment by unsortedhashsets** [comment]
Hi @kahboom, I will do it

**Comment by kahboom** [comment]
thanks @unsortedhashsets , I have invited you to the Kaoto org as well, and this way you can assign/unassign yourself to whichever issue you'd like

**Comment by kahboom** [comment]
completed via https://github.com/KaotoIO/kaoto-ui/pull/1385
