### ISSUE TITLE
Remove default values from YAML

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1396]
### Please describe the feature that you want to propose

Due to the implementation of showing default values (#1154), we are now showing all values in the YAML, which looks a bit messy. We need to confirm with UX about how to correctly approach default values in a consistent manner, but we should remove the excess code from the YAML in the meantime.

![File](https://user-images.githubusercontent.com/3844502/223103097-24da183a-57d9-4327-8e68-61dabca11253.png)

**Comment by kahboom** [comment]
@apupier @Delawen what was decided for this issue then? is this going to be done on the backend or frontend? I thought we agreed that the backend would compare values and remove anything that is equal to the default value, but it seems the backend issue was closed?

**Comment by Delawen** [comment]
I would say it is a duplicate.

**Comment by Delawen** [comment]
And the implementation is almost merged https://github.com/KaotoIO/kaoto-backend/pull/561
