### ISSUE TITLE
http step extension shows an error on first load

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-ui#1416]
### Describe the Bug

The http step extension shows an error on first load. It's usually rerendered in seconds but sometime it persists and need to manually reopen the tab.

### Steps to Reproduce the Bug or Issue

1. Change DSL type to KameletBinding
2. add http-source
3. click added http-source
4. click entended configuration tab

### Screenshots or Videos

https://user-images.githubusercontent.com/265462/223808202-0a84a2a7-0554-4766-960d-f0e4ff44e8d6.mp4

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by apupier** [comment]
note: I reproduce with Chrome but not with Firefox
