### ISSUE TITLE
Support `duration` type of fields in config panel

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1432]
### Please describe the feature that you want to propose

Currently, duration types are not supported, only the name of the field is displayed but it is not possible to define it.

This is a common type, used for instance for `period` on `timer`. See https://camel.apache.org/manual/faq/how-do-i-specify-time-period-in-a-human-friendly-syntax.html

Ideas to split in iterations:
- Provide a text field
- Provide a tooltip on/close to the text field
- Provide validation on the text field. The Camel Catalog is providing [api to validate duration](https://github.com/apache/camel/blob/05595854aadb81ccb408c1ca8c3c28c4dc835ec3/core/camel-core-catalog/src/main/java/org/apache/camel/catalog/impl/AbstractCamelCatalog.java#L149)
- Provide a specific widget

**Comment by kahboom** [comment]
Don't forget to add the label the issue corresponds to (where possible), so it's easy for us to see if it's related to (for example) the step detail or code editor, and this way we can quickly find if an issue already exists for it

**Comment by lordrip** [comment]
Assigning it to @Delawen since she has more knowledge about where is this coming from.

**Comment by lordrip** [comment]
For context, this issue it's because from the `duration` type gets translated into `object` for the UI, and then there's no mechanism in place to infer what it's the actual type.

https://github.com/apache/camel/blob/main/components/camel-timer/src/generated/resources/org/apache/camel/component/timer/timer.json#L34

**Comment by lordrip** [comment]
According [to the link](https://camel.apache.org/manual/faq/how-do-i-specify-time-period-in-a-human-friendly-syntax.html) that @apupier provided, it might be beneficial to treat the `duration` type as `string`, to be able to handle inputs like `45m`, `30s`, etc...
