### ISSUE TITLE
Always select a tab by default in config panel

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1433]
### Please describe the feature that you want to propose

When switching between Step having a Step Extension and some that are relying on the default, there is no tab selected in the Config panel
![noTabSelectedInConfigPanel](https://user-images.githubusercontent.com/1105127/224257111-0f33ef5f-a824-4169-aba7-2cab267b49d4.gif)

**Comment by unsortedhashsets** [comment]
I would rather say it is a bug:

ConfigTab use `useState` with the default value `configTabIndex`, but it works only for the initial Tab open, with clicking on another element it use `useEffect` without change of `configTabIndex` but it can be different for example here Choice config tab is extension and it has index 0 so without useEffect if you click on some other  step you will see a tab with index 0 and also in reverse after some general step you open choice with configtab index 2

**Comment by kahboom** [comment]
Relates to #1280
