### ISSUE TITLE
Dead link in description of Kamelets in Settings

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1437]
### Describe the Bug

deadlink to https://camel.apache.org/camel-k/1.9.x/kamelets/kamelets.html

### Steps to Reproduce the Bug or Issue

1. Go to settings
2. Click on question mark help icon for Type
3. Click on the link here in Kamelet text
4. It opens a 404 on page https://camel.apache.org/camel-k/1.9.x/kamelets/kamelets.html

### Screenshots or Videos

![deadlink](https://user-images.githubusercontent.com/1105127/224262992-3cb54bfe-2d6b-4026-82d8-9b7fe7d302f4.gif)

### Platform

OperateFirst

**Comment by unsortedhashsets** [comment]
Hi @apupier WDYT to change 
hardcoded - `href={'https://camel.apache.org/camel-k/1.9.x/kamelets/kamelets.html'}`
to `latest` - href={'https://camel.apache.org/camel-k/latest/kamelets/kamelets.html'}` now latest redirects to https://camel.apache.org/camel-k/1.12.x/kamelets/kamelets.html :thinking:
