### ISSUE TITLE
Hide parameters that are not supported in the default config panel

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-ui#1444]
### Describe the Bug

If you open up the config panel for a step you will often find bold labels which (from a user pov) look like headlines or section headers but instead these are labels of parameters which cannot be changed in the generic step extension. This is a confusing experience for users.

I suggest to not show these parameters at all or at least not making them appear in bold.

### Steps to Reproduce the Bug or Issue

1. drag a component on the canvas (for instance git)
2. click on the component
3. look at the config panel

### Screenshots or Videos

![grafik](https://user-images.githubusercontent.com/435853/224287802-067bd514-1847-4de5-adcd-f41643fbb172.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by kahboom** [comment]
Are these just ways to group the fields below them? If so we definitely would not want to hide them but just improve the UX. In that case it would be covered by one of the other issues about improving fields that we already have open.

**Comment by lhein** [comment]
Nope. We found in another issue I reported about grouping that these bold labels are actually object type parameters we do not support to modify in the generic step extension.

**Comment by kahboom** [comment]
@lhein but then why hide them if not support them better? or override the config tab completely with a step extension?

btw, what do you mean when you say "generic step extension"? because we have the concept of "generic extensions" (#13 ) and "step extensions" as two separate things. 😄

**Comment by kahboom** [comment]
@lhein also don't forget to add labels to these issues so we can find existing issues more easily

**Comment by Delawen** [comment]
For 1.0.0, just remove it or add some warning as to why they can't be configured.

**Comment by igarashitm** [comment]
So we'd want to hide the non-primitive parameters as we have no way to let user configure it, correct? For example `Type` parameter on camel-git has `GitType` as a type. We might exclude by field types in uniforms. We might able to add enum support, but would be for post 1.0.

**Comment by apupier** [comment]
> So we want to hide the non-primitive parameters as we have no way to let user configure it, correct?

hide or make them smaller with an information mentioing that user needs to go to source code editor to edit it (/!\ in thi case, check that the data is not removed the code)

**Comment by igarashitm** [comment]
Removing `object` properties was easy
```diff
diff --git a/src/components/JsonSchemaConfigurator.tsx b/src/components/JsonSchemaConfigurator.tsx
index 1f87a659..a0fdb689 100644
--- a/src/components/JsonSchemaConfigurator.tsx
+++ b/src/components/JsonSchemaConfigurator.tsx
@@ -1,8 +1,8 @@
+import { CustomJsonSchemaBridge } from './CustomJsonSchemaBridge';
 import Ajv from 'ajv';
 import { useRef } from 'react';
 import { AutoForm } from 'uniforms';
 import { AutoFields, ErrorsField } from 'uniforms-patternfly';
-import { CustomJsonSchemaBridge } from './CustomJsonSchemaBridge';
 
 const ajv = new Ajv({
   allErrors: true,
@@ -26,6 +26,11 @@ type JsonSchemaConfiguratorProps = {
   onChangeModel: (configuration: unknown, isValid: boolean) => void;
 };
 
+function getOmitFields(schema: any) {
+  return Object.keys(schema?.properties).map((key) =>
+    schema.properties[key].type === 'object' ? key : undefined
+  );
+}
 export const JsonSchemaConfigurator = ({
   schema,
   configuration,
@@ -46,7 +51,7 @@ export const JsonSchemaConfigurator = ({
       }}
       data-testid={'json-schema-configurator'}
     >
-      <AutoFields />
+      <AutoFields omitFields={getOmitFields(schema)} />
       <ErrorsField />
       <br />
     </AutoForm>
```
But maybe better to show it in gray to indicate the prop exists but cannot configure. Will look a bit more.

**Comment by igarashitm** [comment]
Succeeded to bind a custom field markup, but struggling to apply "disabled" style
![Screenshot from 2023-03-14 19-13-21](https://user-images.githubusercontent.com/265462/225162977-9f576a94-7cb8-4f97-a72c-2e9dc62795bf.png)

The style specified here is somehow ignored... 
https://github.com/igarashitm/kaoto-ui/commit/aad212da5d6c382998eeeeef015fb3425076844f#diff-de1b89306e97afbdd2e03dd06330677116153a86aadbe2a2c22bf99134ee4b06R11

while I do see it in final HTML
```html
<div class="pf-u-disabled-color-100 pf-u-background-color-200">
  Task executor 
  <button aria-describedby="form-group-label-info" aria-disabled="false"
    aria-label="More info for field" class="pf-c-button pf-m-plain pf-c-form__group-label-help" 
    type="button" data-ouia-component-type="PF4/Button" data-ouia-safe="true" 
    data-ouia-component-id="OUIA-Generated-Button-plain-8">
...
  </button>
</div>
```
@kahboom @lordrip any idea?

P.S. I'm a CSS dummy

**Comment by lordrip** [comment]
@igarashitm Maybe it's because of the styles priorities, that being said, what do we want to achieve? a different color for the text?

**Comment by kahboom** [comment]
@igarashitm So, just to be clear you don't want the popover button to be disabled, you are just wanting to show the text in grey so that it looks like it's not an active property, right? Maybe try to add that class to a `<span>` around the text instead of at the `<div>` level.

**Comment by igarashitm** [comment]
@kahboom exactly, and also gray out the background. I just tried with `<span>` without luck... in theory, the class specified on the deepest element should win, right? while I can see the CSS classes are on `<div>` or `<span>` in the output HTML, I can't see those classes in the chrome devtool CSS tab. :upside_down_face: 
```html
<div>
  <span class="pf-u-disabled-color-200 pf-u-background-color-200">
    Task executor
  </span>
  <button aria-describedby="form-group-label-info" aria-disabled="false" aria-label="More info for field" class="pf-c-button pf-m-plain pf-c-form__group-label-help" type="button" data-ouia-component-type="PF4/Button" data-ouia-safe="true" data-ouia-component-id="OUIA-Generated-Button-plain-8">
  ....
  </button>
</div>
```

**Comment by igarashitm** [comment]
Nailed it - we have to add `BackgroundColor` and `Text` here - https://github.com/KaotoIO/kaoto-ui/blob/main/src/App.tsx#L4-L10
