### ISSUE TITLE
Searching for a deployment makes Kaoto crash

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-ui#1447]
### Describe the Bug

Trying to search for a deployment, makes Kaoto crash, this seems to come from @patternfly, a similar issue that @apupier reported a couple of weeks ago because of the parameter reorder.

### Steps to Reproduce the Bug or Issue

1. Go to the hamburger menu at top-left
2. Select `Deployments`
3. Use the search box to look for a specific deployment
4. As soon as a letter is entered, Kaoto crashes with `TypeError: query.trim is not a function`

![image](https://user-images.githubusercontent.com/16512618/224301629-b728c698-41f0-42cc-9033-716113f3c0c5.png)

### Screenshots or Videos

[Screencast from 2023-03-10 12-14-22.webm](https://user-images.githubusercontent.com/16512618/224302185-e92b843d-ae4b-4519-8d8f-e6f1ee5b9290.webm)

### Platform

- OS: [Linux]
- Browser: [Firefox]
- Version: [0.7.2-dev]

**Comment by apupier** [comment]
> a similar issue that @apupier reported a couple of weeks ago because of the parameter reorder.

right. The fix consisted in aligning the patternfly dependencies

**Comment by apupier** [comment]
based on yarn.lock, react-core is asked in several versions:
`"@patternfly/react-core@4.276.6", "@patternfly/react-core@^4.157.3", "@patternfly/react-core@^4.273.1", "@patternfly/react-core@^4.276.6":`
 
and use  `version "4.276.6"`

**Comment by apupier** [comment]
kietools requires ^4.157.3
@patternfly@react-log-viewer requires ^4.273.1

but I do not see why these dependencies would be implied when doing a search for deployments. And anyway, in theory it resolves with latest version of react-core in yarn.lock. Do we have other micro-frontends than step-extensions? (that would use a different version)

**Comment by lordrip** [comment]
> kietools requires ^4.157.3 @patternfly@react-log-viewer requires ^4.273.1
> 
> but I do not see why these dependencies would be implied when doing a search for deployments. And anyway, in theory it resolves with latest version of react-core in yarn.lock. Do we have other micro-frontends than step-extensions? (that would use a different version)

@apupier I believe that we might be facing the same issue about the function parameters switched :thinking:

**Comment by igarashitm** [comment]
Ugh right, breaking change in the minor release...
https://github.com/patternfly/patternfly-react/commit/1995c5f2808e842443483421951b114e1f841fbd#diff-e866d1da7570edec768365d7c93bad516e9921a953f37586488e5d1d72abbe08L99

This change is already in `@patternfly/react-core@4.276.6` which is specified in kaoto-ui package.json, so we'd be better to align with the new arg order I guess... @kahboom WDYT? Otherwise we'll need to downgrade `@patternfly/react-core`.

**Comment by kahboom** [comment]
@igarashitm I think that sounds good, otherwise we'd just be postponing a minor change that we'll have to do eventually anyway
