### ISSUE TITLE
Upgrade zustand to the latest version

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-ui#1494]
### Please describe the task that needs to be done

From this pull request https://github.com/KaotoIO/kaoto-ui/pull/1324

> Bumps [zustand](https://github.com/pmndrs/zustand) from 4.3.3 to 4.3.4.

This is breaking the unit tests because the `createStore` has been removed.
![image](https://user-images.githubusercontent.com/16512618/225563305-87e7efdb-ff3a-4362-abb2-f4500f77b9ca.png)

This has been a warning since few versions now
![image](https://user-images.githubusercontent.com/16512618/225563455-fd7cc48d-52cd-491e-a284-bf59ad9ba52f.png)

**Comment by unsortedhashsets** [comment]
Seems it was done previously with [PR-1515](https://github.com/KaotoIO/kaoto-ui/pull/1515) by @lordrip :+1: 

Can not reproduce it now
