### ISSUE TITLE
Add spacing between parameters in default Config tab

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-ui#1495]
### Describe the Bug

cf. https://github.com/KaotoIO/kaoto-ui/pull/1488

In default step details Config tab, parameters are too close and maybe better to add a bit spacing.

It might need an uniforms custom theme, or just use one of uniforms OOTB theme, as the current style looks like unstyled.
One thing to note is that in current code uniforms and uniforms-patternfly are mixed
https://github.com/KaotoIO/kaoto-ui/blob/4c8159294eabed57d5935ae28f0f3812c8566e2f/src/components/JsonSchemaConfigurator.tsx#L3
I quickly tried to use uniforms-patternfly version of `<AutoForm>` but got a weird error. 
And also check `@kie-tools/uniforms-patternfly` there as `uniforms-patternfly` is deprecated.
https://github.com/aerogear/uniforms-patternfly

### Steps to Reproduce the Bug or Issue

1. Add activemq
2. Click added activemq step

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
Stumbled upon a fixes while investigating https://github.com/KaotoIO/vscode-kaoto/issues/210
