### ISSUE TITLE
Handle `Step id kaoto`

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-ui#1532]
### Describe the Bug

cf. https://github.com/KaotoIO/kaoto-backend/issues/526
cf. https://github.com/KaotoIO/kaoto-backend/pull/545

With the backend side of change for above, now UI default config tab is showing `Step id kaoto` as a configurable property.
UI needs to somehow handle that, I guess.

### Steps to Reproduce the Bug or Issue

1. Add Split step
2. Click added Split step
3. See the bottom of the Config tab

### Screenshots or Videos

![Screenshot from 2023-03-21 14-45-05](https://user-images.githubusercontent.com/265462/226722284-946d6f4e-04f6-40b2-a00e-cfb086ce518a.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by Delawen** [comment]
This is on purpose. The step id is added to the configuration tab on purpose so the UI doesn't need a special treatment for a property that is DSL dependant.

**Comment by kahboom** [comment]
>This is on purpose. The step id is added to the configuration tab on purpose so the UI doesn't need a special treatment for a property that is DSL dependant.

@Delawen what needs to be done for this issue then?

**Comment by igarashitm** [comment]
Duplicate of #1534
