### ISSUE TITLE
Default config tab using id instead of title?

### ISSUE THREAD

**Issue by Delawen** [KaotoIO/kaoto-ui#1534]
### Describe the Bug

It looks like the configuration tab for steps is not using the title for the label of the fields and is instead using the id.

### Steps to Reproduce the Bug or Issue

1. Add a `split` to a route
2. Open Config tab
3. "Step id kaoto" is not the title of the property. The title of the property is "Step ID". Instead, "step-id-kaoto" is the id of the field.
![image](https://user-images.githubusercontent.com/726590/226831165-ea51f9a7-cb0b-4abf-8a04-76d5bcc79593.png)

### Platform

- OS: [Linux]
- Browser: [Firefox]
- Version: [0.7.4-dev]

**Comment by mmuzikar** [comment]
It looks like different steps have different rules for `title`, for example in direct they start with uppercase, but for split title is the same as the id (except for step-id-kaoto).

Currently the field names are autogenerated by Autoform
The aim is probably to have the title be the source of truth always (is that right?), but a possible workaround to be to set a custom field name only if the title is different from the id. WDYT?

**Comment by mmuzikar** [comment]
Here's an example of Autoform guessing with ressilience4j: 
![image](https://github.com/KaotoIO/kaoto-ui/assets/46345469/70d4672e-47d5-41f7-84a6-9c67991246fe)
And here's using the titles of the `split` step: 
![image](https://github.com/KaotoIO/kaoto-ui/assets/46345469/348e3b4a-9dad-4d4e-bcc7-9e5686fbce97)

**Comment by lordrip** [comment]
> It looks like different steps have different rules for `title`, for example in direct they start with uppercase, but for split title is the same as the id (except for step-id-kaoto).
> 
> Currently the field names are autogenerated by Autoform The aim is probably to have the title be the source of truth always (is that right?), but a possible workaround to be to set a custom field name only if the title is different from the id. WDYT?

This is surprising 👀, were you able to identify in which cases the ID or the Title is used?
