### ISSUE TITLE
Config panel is closing when editing text fields of a step inside a branch in VS Code

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1553]
### Describe the Bug

* Create route with a choice with 2 branches
* add steps on each of the branch
* select one
* type something in a text field
--> the config panel is closing

### Steps to Reproduce the Bug or Issue

* Create route with a choice with 2 branches
* add steps on each of the branch
* select one
* type something in a text field
--> the config panel is closing

Note that sometimes it is not happening but most of the time it is

### Screenshots or Videos

![closingConfigPanel](https://user-images.githubusercontent.com/1105127/227523929-fa690716-3ca4-440a-a453-9f2260de3863.gif)

### Platform

VS Code using main branch of Kaoto UI

**Comment by apupier** [comment]
I suspect a side effect of https://github.com/KaotoIO/kaoto-ui/pull/1544

**Comment by lordrip** [comment]
This issue is also related to accessing values of one step from another

![Image](https://user-images.githubusercontent.com/16512618/227900039-fea97a81-b82e-4a68-aad1-a4fdfbfa6bcc.png)

**Comment by lordrip** [comment]
It's also worth mentioning that the namespace property it's also changing between syncs

![image](https://user-images.githubusercontent.com/16512618/228199397-078f5b79-cf34-43a8-ba24-9c032a774cf3.png)
