### ISSUE TITLE
Sometimes the provided data in config panel field are ignored

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1561]
### Describe the Bug

Sometimes the provided dat avalues are ignored. i wasn't able to determine steps to reproduce but it happens quite regularly (like very 4 or 5 times I try to modify a different step)

I found only this stack in log:
```
stepsService.ts:539 Uncaught TypeError: Cannot set properties of undefined (setting 'value')
    at stepsService.ts:539:44
    at Array.forEach (<anonymous>)
    at StepsService.updateStepParameters (stepsService.ts:537:33)
    at Object.<anonymous> (Visualization.tsx:149:20)
    at invokeFunc (index.js:160:1)
    at trailingEdge (index.js:207:1)
    at timerExpired (index.js:195:1)
 ```

### Steps to Reproduce the Bug or Issue

Not found

### Screenshots or Videos

![dataVanished](https://user-images.githubusercontent.com/1105127/227961929-340c03dc-47a3-45c6-b5d0-d433777f043f.gif)

### Platform

- OS: Fedora
- Browser:  VS Code and Firefox with OperateFirst
- Version: 0.7.5 and main branch on operateFirst

**Comment by unsortedhashsets** [comment]
Hi @lhein more description of how to replicate here - [1576](https://github.com/KaotoIO/kaoto-ui/issues/1576)
