### ISSUE TITLE
Some number properties are grayed out

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-ui#1594]
### Describe the Bug

The `delay` and `period` properties of the `Timer` are supposed to be `number`, so should show the number input field, but currently it's disabled

### Steps to Reproduce the Bug or Issue

1. Add Timer
2. Click added Timer

### Screenshots or Videos

![Screenshot from 2023-03-30 09-26-34](https://user-images.githubusercontent.com/265462/228851526-09a32178-4030-41eb-9960-3c69315a2977.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by apupier** [comment]
they are duration, not number. see https://github.com/KaotoIO/kaoto-ui/issues/1432

**Comment by igarashitm** [comment]
Duplicate of #1432
