### ISSUE TITLE
Improve Step Extension Example

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#160]
The current step extension example is pretty awful, it would be good to see this improved a bit, maybe with a form or something.

**Comment by Delawen** [comment]
Duplicated by #214

**Comment by kahboom** [comment]
@Delawen - Why have you closed this as a duplication? We are currently showing a default Step Extension that is just a button, so either we remove it and don't show any at all, or we improve it. The documentation is a separate thing to me, that is waiting on the Step Extension API to be developed.

**Comment by kahboom** [comment]
I wonder if we still need this issue, or maybe with the step-extension-repository that would be enough?
