### ISSUE TITLE
SyntaxError: Expected ',' or '}' after property value in JSON at position 49357

### ISSUE THREAD

**Issue by unsortedhashsets** [KaotoIO/kaoto-ui#1624]
### Describe the Bug

During E2E tests on Monday (03.04.23) faced the issue during work with fixture: https://github.com/KaotoIO/kaoto-ui/blob/main/cypress/fixtures/EipAction.yaml

Also same error with example provided @kahboom in [issue-1297](https://github.com/KaotoIO/kaoto-ui/issues/1297)

previously it worked
 
Error:
```
SyntaxError: Expected ',' or '}' after property value in JSON at position 49357
(anonymous) @ apiService.ts:192
rejected @ tslib.es6.js:119
Promise.then (async)
step @ tslib.es6.js:120
fulfilled @ tslib.es6.js:118
Promise.then (async)
step @ tslib.es6.js:120
(anonymous) @ tslib.es6.js:121
__awaiter @ tslib.es6.js:117
fetchIntegrationJson @ apiService.ts:177
handleChanges @ SourceCodeEditor.tsx:73
updateModelFromTheEditor @ SourceCodeEditor.tsx:141
onCustomClick @ CodeEditorControl.js:32
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
```

### Steps to Reproduce the Bug or Issue

1) Go to the homepage
2) Source code -> Clear
3) Start from scratch
4) Copy and paste one from the examples above

### Screenshots or Videos

![chrome-capture-2023-3-4 (3)](https://user-images.githubusercontent.com/46084942/229756113-3b85e3c7-2ab7-466e-a7a4-ed2785321d88.gif)

### Platform

- OS: [Red Hat Enterprise Linux 8.6]
- Browser: [Chrome, Firefox]
- Version: [110.0.5481.177, 111.0]

**Comment by unsortedhashsets** [comment]
> good chance that it is a duplicate of [KaotoIO/kaoto-backend#583](https://github.com/KaotoIO/kaoto-backend/issues/583)

Yes, seems so, but e2e tests started to crash only yesterday not last week :thinking:

**Comment by apupier** [comment]
with PR https://github.com/KaotoIO/kaoto-backend/pull/606 created to fix https://github.com/KaotoIO/kaoto-backend/issues/583 , I do not have errors when clicking on `sync code` with example from https://github.com/KaotoIO/kaoto-ui/issues/1297

>  but e2e tests started to crash only yesterday not last week
I'm wondering if it is that previously the data were removed instead of sending invalid data

**Comment by unsortedhashsets** [comment]
FYI @apupier today seems to be fixed with new main backend image 😀 => I close that issue
