### ISSUE TITLE
Export route as png

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#1708]
### Please describe the feature that you want to propose

it would be nice to export routes as png file.

1. ~As first iteration export all routes in the canvas.~ #1762
2. As a second might be nice to be able to export a single route at a time #1781 
3. As a third iteration to be able to select which route to export (but maybe not worthy) #1781

**Comment by kahboom** [comment]
hey @lordrip 🙂  was this not already finished? probably best to assign yourself and update the status to prevent any duplication

**Comment by kahboom** [comment]
ah nevermind i see there are more steps

**Comment by lordrip** [comment]
😄 yes, I didn't want to close it as we have more iterations to do. That being said, I think that you raise a good point, if we keep the issue open, it will be open for the milestone, what if I extract the next iterations into other issues?

**Comment by kahboom** [comment]
Hmm I wonder if this is big enough to be an epic

>what if I extract the next iterations into other issues?

I like that idea but I leave it to you, I think either way is fine. 😄
