### ISSUE TITLE
REST DSL UI

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1720]
### Please describe the feature that you want to propose

Add the ability to visualize routes that use the REST DSL

## Tasks
- Use `capabilities` endpoint to provide support for REST DSL-specific language (for example, not `"branches"` but `"endpoints"` and `"operation"` for mini catalog)
- Flow or step-specific styling to look more like a REST API visualization tool

Required issue for backend work: #1246 

Backend issue: https://github.com/KaotoIO/kaoto-backend/issues/224

**Comment by Delawen** [comment]
Shouldn't this be a step extension?

**Comment by kahboom** [comment]
No, the first task of getting REST DSL-specific language is not specific to a step, but more cross-cutting (for example we would use language provided within the catalog).

The styling for nodes we still did not decide if it would be specific to the flow or the step, but that's still not a step extension, rather, another call to the API.

What step extension were you referring to @Delawen ?

**Comment by Delawen** [comment]
![image](https://user-images.githubusercontent.com/726590/235904085-e5063f08-c763-454d-af2a-4f52440e12fe.png)

1.- A step extension on the `rest` step that allows to:
 - Link to or upload an openapi file 
 -  Generate the rest of the structure (get/post/delete... + consumes) based on that openapi
 - Add buttons to add GET/POST/....
 
[Optionally]  2.- A step extension on GET/POST/.... with a button to add new `consumes`

**Comment by lordrip** [comment]
#### Mini Catalog
    ![image](https://github.com/KaotoIO/kaoto-ui/assets/16512618/2b4cbcbf-22b4-411d-a7c4-150fb60f4139)

#### Step extension
![image](https://github.com/KaotoIO/kaoto-ui/assets/16512618/1f167556-66f0-4f9b-a395-09df7020b2d7)

#### Loading an OpenAPI definition
![image](https://github.com/KaotoIO/kaoto-ui/assets/16512618/ec9540db-33ed-4759-8d51-04fee0ba3e4b)

#### OpenAPI Loaded
![image](https://github.com/KaotoIO/kaoto-ui/assets/16512618/ae20319e-c972-422f-becf-9a6f9fdcfef9)
