### ISSUE TITLE
Help Feature

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-ui#1737]
### Please describe the feature that you want to propose

There is currently a disabled menu item for "Help". Implement a help function.

**Comment by tplevko** [comment]
@lhein the "help" menu item is already enabled
![Screenshot from 2023-05-29 10-16-10](https://github.com/KaotoIO/kaoto-ui/assets/4180208/67ba706a-ed7d-4183-b390-a371a0c2d42c)
