### ISSUE TITLE
[BUG/E2E] Missing/wrong connection in nested branches, problems with deletion and replace

### ISSUE THREAD

**Issue by unsortedhashsets** [KaotoIO/kaoto-ui#1776]
### Describe the Bug

Hi,

During e2e tests faced the issue that looks like previously appeared issues (1288, 1347).

10-branching_actions_from_canvas/nested_branches_from_canvas.cy.js
1) User appends a step in a nested branch from the canvas (last in the branch)
![append-step](https://github.com/KaotoIO/kaoto-ui/assets/46084942/a6e26c9b-783b-4a7a-ae04-a12621d623ec)

2) User prepends a step in a nested branch from the canvas (first in the branch)
![prepend-step](https://github.com/KaotoIO/kaoto-ui/assets/46084942/78c552e8-cc18-4e64-9547-1c13d423cf22)

Also two new problems with delete and replace actions in nested branches:

10-branching_actions_from_canvas/nested_branches_step_actions_from_canvas.cy.js
1) User deletes a step in a branch
![delete-step](https://github.com/KaotoIO/kaoto-ui/assets/46084942/8d615fd3-d2b8-4c11-a03b-3e101640f883)
(works only after two times delete clicks)

2) User replaces a step in a branch
![replace-step](https://github.com/KaotoIO/kaoto-ui/assets/46084942/63860b8f-de57-41ca-be45-a12ae78141f4)
(First I try to replace activemq with aggregate then empty step (which is ok))

Was tested with main backend => maybe it is backend issue

### Steps to Reproduce the Bug or Issue

1) Use [fixture](https://github.com/KaotoIO/kaoto-ui/blob/main/cypress/fixtures/EipAction.yaml)
2) Add nested branches after the second `Choice` step
3) Replace the empty step with some step (activemq on GIFs)
4) Try to append / prepend / delete / D&D replacethe 

### Platform

- OS: [Windows, Linux]
- Browser: [Chrome, Edge, Firefox]

**Comment by lordrip** [comment]
Hi @unsortedhashsets , this might be related to the multiple flows support, I'll take a look

**Comment by unsortedhashsets** [comment]
> Hi @unsortedhashsets , this might be related to the multiple flows support, I'll take a look

Hi @lordrip!

For today seems to be fixed (do not know how, may be -> https://github.com/KaotoIO/kaoto-ui/pull/1770 hellped) all workflows have passed :open_mouth: 
The issue existed for 3 previous days 

So I close that issue and will  reopen it if find some strange behavior
