### ISSUE TITLE
E2E tests flaky in CI/CD

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#1811]
### Please describe the task that needs to be done

Cypress is occasionally timing out in CI/CD flows, unable to reproduce locally in headless mode. See the following PR for failures in Chrome and Edge: https://github.com/KaotoIO/kaoto-ui/pull/1805

**Comment by tplevko** [comment]
@lordrip can we close this issue? I believe there were several e2e PR's related to stability improvements, currently I can say the tests are quite stable - https://github.com/KaotoIO/kaoto-ui/actions/workflows/e2e-tests.yml

In case there is requirement for further e2e stability improvements, I think we can create new issue.

**Comment by lordrip** [comment]
I agree, look how much green it is now :eyes:, thanks @tplevko :muscle: 

![image](https://github.com/KaotoIO/kaoto-ui/assets/16512618/17bda776-40f0-47c7-bc33-6ca6d3355951)
