### ISSUE TITLE
Cannot change to the `Integration` type

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-ui#1848]
### Describe the Bug

Can't change the DSL `Type` to `Integration`. It seems changing, but it gets back once source code editor is opened.

### Steps to Reproduce the Bug or Issue

1. Go to Settings
2. Change the Type to Integration and click Save button
3. Go to Settings, see that the `Type` is still `Integration`
4. Open the source code editor
5. You can see the source code is Camel Route
6. Go to Settings
7. Type is shown Camel Route

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
This issue was handled in the associated pull request.
