### ISSUE TITLE
When using kaoto code editor for editing multiple routes - after sync only first route stays displayed

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-ui#1910]
### Describe the Bug

When users use the code editor for editing multiple routes with displayed route in the canvas, after syncing the code editor the displayed routes are hidden and only the first route stays displayed.

### Steps to Reproduce the Bug or Issue

1. create multiple routes
2. display second route 
3. edit the second route in editor
4. sync editor
5. see the route displayed is now the first route

### Screenshots or Videos

![Peek 2023-06-06 08-59](https://github.com/KaotoIO/kaoto-ui/assets/4180208/6f521bfa-5838-4781-8aab-d1edba3c30d9)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

**Comment by lordrip** [comment]
I never thought that I would ever say this, but this is not a `bug` but a `feature` :sweat_smile: :see_no_evil: 

Jokes aside, showing only the first route is the "intended" behavior, but now that you raise this topic, I'm wondering if this might be confusing to the user. I'll ask for feedback in the meantime, to provide a different behavior.

**Comment by tplevko** [comment]
Thanks @lordrip for the response. I still believe this might be an issue, as the route which stays displayed in the canvas might not be the one the user was editing - the current behaviour leaves open the first route from the route list.

The "only route displayed" would be OK I think, in case the one route displayed after the source code edit sync was the one the user was editing.
