### ISSUE TITLE
When deleting all routes, the last one stays in the code editor  

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-ui#1911]
### Describe the Bug

When deleting the last route, the code editor has it still displayed even after the route disappears from the canvas.

### Steps to Reproduce the Bug or Issue

1. create a route
2. delete the route - having none left
3. see the last route stayed in the code editor

### Screenshots or Videos

![Screenshot from 2023-06-05 15-32-23](https://github.com/KaotoIO/kaoto-ui/assets/4180208/13c203d7-dde7-4a41-b901-a6e4c107a744)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

**Comment by lordrip** [comment]
Fixed with https://github.com/KaotoIO/kaoto-ui/pull/1923/files#diff-8f61b7fec75e39c47c8797ac16a3734367b71330493ba4bc509dfbc1cde76ce0R184
