### ISSUE TITLE
Merge step extension template repository with step extensions repository

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-ui#1912]
### Context
Currently, we have these three step extension related repositories:

1. https://github.com/KaotoIO/step-extension-repository (where all extensions are hosted)
2. https://github.com/KaotoIO/step-extension-template (the template step extension)

### Goal
This issue aims to merge [repo #2](https://github.com/KaotoIO/step-extension-template)  into [repo #1](https://github.com/KaotoIO/step-extension-repository). By doing this, we will gain:

* By updating a dependency from a step extension, the template will be upgraded as well, reducing the number of open pull requests
* Keeping the same folder structure across the step extensions will be easier.
* Having step extensions related issues in one single place. (This would be even better once we move the step extensions to the Kaoto UI repo)

### Considerations
Once the repositories are merged, we need to make sure that we:
- [x] Move the step extension template to the step extensions repository https://github.com/KaotoIO/step-extension-repository/pull/940
- [x] Do not remove the repository but archive it with a message pointing to this issue and the location of the new repository
- [x] Disable all the automation from [repo #2](https://github.com/KaotoIO/step-extension-template), including `dependabot`.
- [x] Add a `--exclude step-extension-template` in the build process of the [repo #1](https://github.com/KaotoIO/step-extension-repository) to do not build nor test the template.
- [x] The step extension template should be included in the `yarn workspaces definition`
- [x] Update the docs that point to the step extension template

**Comment by tplevko** [comment]
Added info to the template Readme file - https://github.com/KaotoIO/step-extension-template/pull/124

@lordrip I don't have permissions required to archive the template repository and disable the automation and dependabot. Could you point me to someone who could help me with this?

**Comment by lordrip** [comment]
I tried myself without success. @Delawen could you help us here? pretty-please :pray:

**Comment by lordrip** [comment]
We would need to update the [kaoto website](https://kaoto.io/docs/add-custom-view/) to show this change.

![image](https://github.com/KaotoIO/kaoto-ui/assets/16512618/db68b3d0-ec98-4530-9e94-1a83e3884b90)

**Comment by tplevko** [comment]
> We would need to update the [kaoto website](https://kaoto.io/docs/add-custom-view/) to show this change.
> 
Thanks @lordrip, updated the website here - https://github.com/KaotoIO/kaoto.io/pull/44

**Comment by tplevko** [comment]
@lordrip as the repo was already archived - closing this issue as done.
