### ISSUE TITLE
Set focus to Name field when adding a new Bean

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#2002]
### Please describe the feature that you want to propose

Currently, the new bean is selected in the left panel and has the focus. To start typing, needs to either click in the first field name or to hit tab 6 times

**Comment by igarashitm** [comment]
@lordrip do you think this is possible with uniforms? Even if we managed to put `autoFocus` on a first required field, doesn't it then enforce the focus to the `Name` field on every rerendering?

**Comment by igarashitm** [comment]
Found a way to focus programmatically - #2012
