### ISSUE TITLE
Can't remove end step from integration using the source code editor

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-ui#2018]
### Describe the Bug

Users can't remove end step from integration using the source code editor from Kamelet Binding route. 

Tried both approaches - removing the whole `sink` step and replacing it with `sink: null`, none of which work.

### Steps to Reproduce the Bug or Issue

1. create Kamelet Binding with source and sink steps
2. try removing the sink step in source code editor
3. see the sink step is not removed

### Screenshots or Videos

![Peek 2023-06-22 10-59](https://github.com/KaotoIO/kaoto-ui/assets/4180208/1d15821e-3488-497b-9860-03afc24e27a9)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

**Comment by tplevko** [comment]
@Delawen I think this might be related to recent changes https://github.com/KaotoIO/kaoto-backend/pull/694

**Comment by Delawen** [comment]
This bug no longer applies, it must have been solved at some point in another issue.
