### ISSUE TITLE
Load balance strategy are not saved

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#2052]
### Describe the Bug

Load balance strategy are not saved

### Steps to Reproduce the Bug or Issue

1. create a Camel route
2. add a timer
3. add a load-balance
4. change load balance strategy
--> nothgn is aved in source code

### Platform

red.ht/kaoto-snapshot

**Comment by lordrip** [comment]
Fixed by https://github.com/KaotoIO/kaoto-ui/issues/2052
