### ISSUE TITLE
Sort step extension is not saving anything

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#2053]
### Describe the Bug

Sort step extension is not saving anything

in console:
```
Uncaught TypeError: newStepParameters[paramIndex] is undefined
    updateStepParameters stepsService.ts:490
    updateStepParameters stepsService.ts:488
    saveConfig Visualization.tsx:243
    kaotoApi VisualizationStepViews.tsx:178
    onClick SortStep.tsx:64
```

### Steps to Reproduce the Bug or Issue

1. Create a Camel route
2. add a timer
3. add sort
4. select sort
5. in Config tab, fill some values
6. Clcik apply
--> fields are cleared and nothign is saved in source

### Platform

red.ht/kaoto-snapshot

**Comment by lordrip** [comment]
Fixed by https://github.com/KaotoIO/kaoto-ui/issues/2053
