### ISSUE TITLE
Issues with autogenerated route name

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-ui#2054]
### Describe the Bug

There is new auto-generated field, created for generated routes - "metadata:name", which has a form of `Route Kind + generated number`

There seems to be few issues with this field, e.g. - The field gets regenerated every time users add new route. Also the generated number is same for the added routes, just added two times for the second route. For the third route onwards - it's the same as the number specified for the second route. 

### Steps to Reproduce the Bug or Issue

1. add several routes
2. see the "metadata:name" fields changing values

### Screenshots or Videos

![Peek 2023-06-27 13-27](https://github.com/KaotoIO/kaoto-ui/assets/4180208/7f78228c-c35a-41a7-875e-beaf90e0863e)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

**Comment by Delawen** [comment]
My guess is the new route is generated with the same name as the previous route and then the backend adds the currenttimemillis to make sure they are unique. (Now it will use a smaller number but)

**Comment by tplevko** [comment]
This specific issue seems not to be present anymore in the UI. Closing.
