### ISSUE TITLE
Deleting last route from the canvas doesn't get reflected in the code editor

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-ui#2086]
### Describe the Bug

When users delete the route using the delete dropdown - the route sources stay in the code editor.

### Steps to Reproduce the Bug or Issue

1. create a route
2. specify route steps
3. delete the route using the dropdown
4. see the route source remains in the code editor

### Screenshots or Videos

![Peek 2023-07-03 09-38](https://github.com/KaotoIO/kaoto-ui/assets/4180208/80ae4f34-4455-440e-bc2d-fd3710d18f90)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [last]

**Comment by igarashitm** [comment]
It might be related to or same root cause with #2077

**Comment by igarashitm** [comment]
When a user clicks the route delete button, the frontend is supposed to send an empty Kaoto JSON and get the empty YAML, but it doesn't. Only `view-definitions` request is observed.
