### ISSUE TITLE
Add option for adding two or more branches to single action/end step

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-ui#2094]
### Describe the Feature

Currently, there is only option for adding the branches in one action/end step, or create for every branch it's action or end step.
The attached screenshot is an proposal, how the connected steps could look like. It's not not doable with the current UI.

### Screenshots or Videos

![Screenshot from 2023-07-04 08-46-19](https://github.com/KaotoIO/kaoto-ui/assets/4180208/657b956e-03d9-48b7-8072-c9f326a334de)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

**Comment by igarashitm** [comment]
https://github.com/KaotoIO/kaoto-ui/issues/2095#issuecomment-1621614803

**Comment by Delawen** [comment]
This is not... doable in Camel, right? Why do we want to add a feature that is not supported by Camel?

**Comment by tplevko** [comment]
This can be achieved with "direct" component, further specifying the routes as separate ones. So you are right, this is not supported in camel in the way I proposed, so closing
