### ISSUE TITLE
When creating a deployment that fails, no error message is shown

### ISSUE THREAD

**Issue by Delawen** [KaotoIO/kaoto-ui#2125]
### Describe the Bug

Trying to create a deployment always return a success message, even in case of failure.

Relates to https://github.com/KaotoIO/kaoto-ui/issues/1450

### Steps to Reproduce the Bug or Issue

1.- Create an invalid integration (for example, a Binding with only one step).
2.- Deploy it
3.- I was expecting a BOOM but instead got a green success message.

### Screenshots or Videos

On unstable we return a method not allowed

![image](https://github.com/KaotoIO/kaoto-ui/assets/726590/12d6557f-9135-423b-9901-3392ce1e2c00)

But we don't care?
![image](https://github.com/KaotoIO/kaoto-ui/assets/726590/30cc833f-6b76-4ad6-a543-a2cd958cb876)

### Platform

- OS: Linux
- Browser: Firefox
- Version: 1.1.0-M1

**Comment by lordrip** [comment]
Closing it in favor of: https://github.com/KaotoIO/kaoto-ui/issues/2201
