### ISSUE TITLE
Contextual Mini Catalog

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#216]
Add support for a "mini catalog" that loads a list of steps. The idea is that when a user wants to add a new step to an existing step, they will click a + button that loads a searchable mini catalog of steps compatible with it. The user can then select the step, which will automatically be appended to the existing step.

### Steps
- [x] [Update apiService to use new endpoint](https://kaotoio.github.io/kaoto-backend/api/index.html#api-StepResource-stepGet)
- [x] Add component for Contextual Mini Catalog
- [x] Add handler for selecting steps
- [x] Verify validation is in tact, add tests
- [x] Add search

Depends on https://github.com/KaotoIO/kaoto-backend/issues/42 and either #218 or #219 for the final implementation, but development can start before then.

**Comment by Delawen** [comment]
Reopening because we still need to add new endpoint (working on it)

**Comment by Delawen** [comment]
#42
