### ISSUE TITLE
Code syncing issue when editing beans

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-ui#2168]
### Describe the Bug

Once users rename the bean, the previously created properties for this bean can't be removed.

EDIT - 
This issue seems to be more general, not affecting the beans only in the above mentioned case, but in general, when only one action is performed - the backend sync seems to be performed only after second change in the UI.

### Steps to Reproduce the Bug or Issue

1. create a bean
2. specify name and type
3. add properties
4. rename the bean
5. try to delete previously created properties - see the properties stayed in the code editor

### Screenshots or Videos

![Peek 2023-07-20 11-50](https://github.com/KaotoIO/kaoto-ui/assets/4180208/4603e1dd-9da4-452e-ae39-8c99b08cd81b)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

**Comment by tplevko** [comment]
Recording:
![Peek 2023-07-20 13-15](https://github.com/KaotoIO/kaoto-ui/assets/4180208/436fdfc7-b409-408a-896f-09c45d469b71)

**Comment by igarashitm** [comment]
Decided to remove onBlur auto save and introduce manual save/cancel button for MetadataEditor. Because of that we no longer need a placeholder row, i.e. #2169 will also be addressed.
