### ISSUE TITLE
Insert Step from Visualization

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#219]
Add the ability to insert a new Step between two existing Steps from the Visualization. There are two ways the user should be able to do this:

- The user clicks a "+" button on the last step, which inserts a slot between the two steps. The user can then drag a step from the Catalog onto the slot.
- The user clicks a "+" button on the last step, which inserts a slot between the two steps. A mini catalog (#216 ) opens up, and the user can then choose the step to be aggregated/appended.

It's not entirely clear if both ways will be possible or intuitive to the user. A story should be created for each to see which option would be best to start with.

See this issue for more information: #218 <-- we should be following the same decision for both ways of adding a step

---

### Steps

- [ ] Add validation for inserting a step
- [ ] Add custom edge
- [ ] Add logic to show a slot
- [ ] Create stories for both scenarios described above
- [ ] Implement changes onto Visualization

**Comment by Delawen** [comment]
Shouldn't this be closed with #216 ?

**Comment by lhein** [comment]
#342 seems closed. This should unblock the issue, right?

**Comment by kahboom** [comment]
> #342 seems closed. This should unblock the issue, right?

@lhein sheesh it was just merged today 😂

**Comment by kahboom** [comment]
> #342 seems closed. This should unblock the issue, right?

@lhein kidding aside, yes this should unblock it for @mmelko

**Comment by lhein** [comment]
:D I did not check dates. Was just curious ;)

**Comment by Delawen** [comment]
:partying_face: :balloon:
