### ISSUE TITLE
Fix issue with Add Step slot replacement

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#231]
There is a new bug with the slot replacement after Append Step was added.

Steps to reproduce:
1. Create a multi-step integration using the YAML editor, or use the one loaded by default.
2. Delete the first step (source).
3. Open the catalog.
4. Drag a source step onto the "Add Step" slot.

The UI breaks, see screenshot below.

![Screen Shot 2022-03-01 at 4 12 43 pm](https://user-images.githubusercontent.com/3844502/156205689-36545b4e-44cd-496d-806a-b92345c7dee1.png)

Also, we should add E2E tests to ensure this doesn't happen again.

**Comment by kahboom** [comment]
This would likely be resolved with the following: https://github.com/KaotoIO/kaoto-backend/issues/46

**Comment by Delawen** [comment]
https://github.com/KaotoIO/kaoto-backend/pull/47
