### ISSUE TITLE
 Hope to support lower version of camel 3.14.9

### ISSUE THREAD

**Issue by Seifon** [KaotoIO/kaoto-ui#2333]
### Please describe the feature that you want to propose

 Hope to support lower version of camel

camel version: 3.14.9

java version: 1.8

 Because the company project is still using Java 1.8, we have to use the 3.14.9 version of the camel

 It would be even better if it could simultaneously support generating XML Dsl

**Comment by lordrip** [comment]
Hi @Seifon, thanks for filing this issue, unfortunately, this is out of the scope of the project at the moment.

**Comment by lordrip** [comment]
Hi @Seifon , we're working on a UI only version here https://github.com/KaotoIO/kaoto-next

Maybe this could help.
