### ISSUE TITLE
YAML Occasionally Blank/Unsynced

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#247]
This seems to only happen on initial page load, and happens somewhat randomly. Once you make any changes, it seems to sync without issues.

![Screen Shot 2022-03-10 at 12 34 50 pm](https://user-images.githubusercontent.com/3844502/157663014-aea01b26-a960-4ab8-b622-34d428ac1ad2.png)

**Comment by Delawen** [comment]
As there is no initial page load now with initial source code... is this still a problem?

**Comment by kahboom** [comment]
@Delawen - It wasn't always only on initial page load, I have to try to reproduce it again and will close it if I can't.

**Comment by kahboom** [comment]
Can't seem to reproduce it, closing for now and will reopen if it happens again.
