### ISSUE TITLE
Code Editor AutoCompletion

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#251]
Because we want Kaoto to be a good way for users to learn how to use Camel, it would be very convenient to have autocompletion in the code editor.

Related:
- https://github.com/camel-tooling/camel-language-server

**Comment by apupier** [comment]
Completion (and all editing capacities) in the Code Editor can be improved by Camel Language Server a bit but mostly by the [Yaml Language Server](https://github.com/redhat-developer/yaml-language-server) given that Yaml DSL is used and the `uri` tag is not used (if I'm not mistaken).
A good thing would be to associate the yaml schema programmatically but as a first step it can be provided with the `# yaml-language-server: $schema=<urlToTheSchema>` [modeline](https://github.com/redhat-developer/yaml-language-server#using-inlined-schema). This case works well for pure Yaml routes. When it is a Camel CRDs, I think some extra configuration is needed on the client side to either connect to a Kubernetes instance with Camel K CRDs deployed or provide them programmatically.

The yaml language server is written in TypeScript so should be an easy integration. The Camel Language Server is runnign in java, so will need to launch it somewhere and connect it via [websocket connection](https://github.com/camel-tooling/camel-language-server#websocket-support).

If I understand well, the Kaoto Code Editor is [based on Monaco](https://github.com/KaotoIO/kaoto-ui/blob/c12b6fda94247b5581ff82567b0a2604ac5ea94d/src/components/YAMLEditor.tsx#L6)
and it is written in React.

The Monaco client implementation for the language server support is https://github.com/TypeFox/monaco-languageclient I do not know if it integrates well with React.

**Comment by Delawen** [comment]
Can we have both at the same time if we add the uri tag? 

We can deploy the Camel LS with the backend and the YAML LS with the frontend.

**Comment by apupier** [comment]
> Can we have both at the same time if we add the uri tag?

In theory yes, but never tried. It is working in VS code and Eclipse Desktop. It depends on the client support, so on the Monaco Editor client implementation for the Language Server Protocol. (but I do not know this client well)

**Comment by Delawen** [comment]
This was already implemented, why is it still open?
