### ISSUE TITLE
KaotoUI Components are not shown properly

### ISSUE THREAD

**Issue by almen-ng** [KaotoIO/kaoto-ui#257]
When running KaotoUI (Firefox/Chrome), elements are not shown properly including the Step Catalog/YAML Editor/Header.
![image](https://user-images.githubusercontent.com/68764826/158623410-efa345ed-d531-4964-944e-40a87dbd7d92.png)

**Comment by kahboom** [comment]
@almen-ng I think this has been fixed already, I just checked on Firefox. Could you confirm for me though? Thanks!

**Comment by Delawen** [comment]
I confirm this does not happen in Firefox or Chromium.
