### ISSUE TITLE
Undo/Redo for Code Editor

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#269]
It would be useful for users to be able to undo/redo changes they make to the Code Editor.

**Comment by apupier** [comment]
Do you have an idea why the undo/redo is not working out of the box? With the Monaco editor, it should be available by default (I was able to try undo/redo with Ctrl+Z and Ctrl+Y on the [official sample website](https://microsoft.github.io/monaco-editor/index.html)).

**Comment by kahboom** [comment]
@apupier - Thanks! I didn't know that, I will take a look at it this week if I get a chance.
