### ISSUE TITLE
[e2e] Add test for editing properties

### ISSUE THREAD

**Issue by Delawen** [KaotoIO/kaoto-ui#298]
Add a test that edits properties in a similar way than the following example:

![imagen](https://user-images.githubusercontent.com/3844502/162005620-b3b63cbb-499d-45ba-8638-263ea62907ae.gif)

1. Use the following text in the source code text box:
```apiVersion: camel.apache.org/v1alpha1
group: camel.apache.org
kind: KameletBinding
metadata:
  additionalProperties: {}
  finalizers: []
  managedFields: []
  name: Updated integration
  ownerReferences: []
plural: kameletbindings
scope: Namespaced
served: true
singular: kameletbinding
spec:
  source:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      name: timer-source
      kind: Kamelet
  sink:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-sink
      kind: Kamelet
storage: true
version: v1alpha1
```
2. Click on the first step `timer-source`
3. Check the detail window opens
4. Go to `Config` tab
5.  Input `3000` on the `Period` property
6. Check the property gets added to the `timer-source` in the source code
7. Click on the last step `kafka-sink`
8. Check the detail window opens
9. Go to `Config` tab
10. Input `password` in the `password` property
11. Input `topicname` in the `topic` property
12. Check the properties get added to the `kafka-sink` in the source code
13. Change the value of the `Period` property in the source code
14. Click on the first step `timer-source`
15. Go to `Config` tab
16. The value in the input `Period` must be the same as the value from the source code

Tests are defined on: https://github.com/KaotoIO/kaoto-ui/tree/main/cypress
They can be run as described in the README: https://github.com/KaotoIO/kaoto-ui#end-to-end-e2e-tests
You need the backend running to be able to execute the test: https://kaoto.io/quickstart/

**Comment by kahboom** [comment]
@miram13 this was already completed, wasn't it?

**Comment by miram13** [comment]
Ya, it is completed

**Comment by miram13** [comment]
> @miram13 this was already completed, wasn't it?

Ya, it is completed..I'll close the issue.
