### ISSUE TITLE
Single Command for Running API & UI

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#307]
It would be nice to have a single command you can run that loads everything you need for Kaoto (except for deployments, for now). Maybe using Docker Compose?
cc @mmelko

**Comment by mmelko** [comment]
@kahboom currently you can deploy kaoto inside of kubernetes cluster with `kubectl apply -f https://gist.githubusercontent.com/mmelko/0207410efb450ca940d3fd1af0f37bf7/raw/f6d498d6e499640a1828efcb5614792ac7fb4e69/kaoto.yaml`   If  you have camel-k installed in the same namespace you should be able to deploy integrations too.

**Comment by kahboom** [comment]
@mmelko should this be moved to the other repo for the operator? I haven't been able to test yet your last comment.

**Comment by mmelko** [comment]
hmm I believe this can stay here. I've created https://github.com/KaotoIO/kaoto-ui/blob/main/docker-compose.yml. So now API and UI can be run with `docker-compose up`

**Comment by kahboom** [comment]
Thanks @mmelko , marking as `shipped` and closing.

**Comment by kahboom** [comment]
@mmelko we should probably also put this somewhere in the README or on the website as well, so people are aware.
