### ISSUE TITLE
React Flow Migration 9.x -> 10.x

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#342]
**Is your feature request related to a problem? Please describe.**
React Flow `v10.x` provides some really cool features that we will definitely use, like [Sub Flows](https://reactflow.dev/docs/guides/sub-flows/), but we need to migrate from `v9.x` to `v10.x`.

**Additional context**
Follow the [migration guide](https://reactflow.dev/docs/guides/migrate-to-v10/) provided.

**Comment by mmelko** [comment]
I will take this one

**Comment by kahboom** [comment]
Making this a higher priority and stealing it from @mmelko , as we will need to do some layout redesigning soon.
