### ISSUE TITLE
Monitoring: deployment status improvements 

### ISSUE THREAD

**Issue by mmelko** [KaotoIO/kaoto-ui#445]
Currently there is inconsistent information after failed deployment:
 Deployment started, integration deploying, error --> at the same time: 
<img width="1440" alt="Screenshot 2022-05-26 at 09 42 12" src="https://user-images.githubusercontent.com/6814482/170442264-461f602c-c1d6-46af-8306-1be8b8e62c90.png">

Also after tihs I'm not sure how can I get back to the integration

**Comment by kahboom** [comment]
This should be fixed with the new API, but marking this as 'Blocked' until #531 is merged and verified.

**Comment by kahboom** [comment]
waiting on https://github.com/KaotoIO/kaoto-backend/issues/88

**Comment by Delawen** [comment]
If the deployment fails on the `deploy` call/pressing `deploy` button, it throws an error.

If the deployment fails after the `deploy` call, you can see it on the list of deployments.
