### ISSUE TITLE
[E2E] Create test for Undo/Redo actions in the code editor 

### ISSUE THREAD

**Issue by mmelko** [KaotoIO/kaoto-ui#472]
Ensure that Undo/Redo actions are working by triggering them manually using panel buttons.

**Comment by Delawen** [comment]
Waiting for https://github.com/KaotoIO/kaoto-ui/pull/471 to be merged

**Comment by Delawen** [comment]
There are new undo/redo buttons in the editor. Check they work fine by:

 * Creating an integration with several steps
 * Undo
 * Make sure the graphical side gets updated properly
 * Redo
 * Make sure the graphical side gets updated properly
