### ISSUE TITLE
[step-extension] Create extension for HTTP

### ISSUE THREAD

**Issue by Delawen** [KaotoIO/kaoto-ui#487]
Create an extension for https://camel.apache.org/camel-kamelets/latest/http-source.html

Instructions to create a new extension in https://kaoto.io/docs/add-custom-view/

This extension must allow the user to set up all the configuration options of the kamelet and:

 * Upload an openapi specification
 * Show a list of endpoints
 * Let the user select one endpoint
 * Offer a form with all the parameters for that endpoint
 * Configure the step with that endpoint and parameters

EDIT: I've moved the repo to the Kaoto org here: https://github.com/KaotoIO/http-step-extension

**Comment by joshiraez** [comment]
I think I can try this
