### ISSUE TITLE
[step-extension] Create extension for HTTP Sink

### ISSUE THREAD

**Issue by Delawen** [KaotoIO/kaoto-ui#488]
Create an extension for https://camel.apache.org/camel-kamelets/latest/http-sink.html

Instructions to create a new extension in https://kaoto.io/docs/add-custom-view/

This extension must allow the user to set up all the configuration options of the kamelet and:

 * Upload an openapi specification
 * Show a list of endpoints
 * Let the user select one endpoint
 * Offer a form with all the parameters for that endpoint
 * Configure the step with that endpoint and parameters

**Comment by mmelko** [comment]
https://github.com/KaotoIO/http-step-extension
