### ISSUE TITLE
[e2e] Make Kaoto location configurable

### ISSUE THREAD

**Issue by mmelko** [KaotoIO/kaoto-ui#511]
Currently in e2e tests the address is hardcoded:  : `cy.visit('http://localhost:1337');` .
It would be nice to refactor the tests and make the target URL configurable. This would allow to run the tests also against docker image or kaoto running remotely on some cluster.

**Comment by Delawen** [comment]
@miram13 can you check @mmelko comment?

**Comment by miram13** [comment]
Ya Sure
