### ISSUE TITLE
Broken UI on Windows 

### ISSUE THREAD

**Issue by mmelko** [KaotoIO/kaoto-ui#519]
CSS looks broken when running the UI using `yarn start` 
![Screenshot (6)](https://user-images.githubusercontent.com/6814482/174565231-b516a8e2-59c3-49c0-8dd9-cc3ee69f7f37.png)

**Comment by Delawen** [comment]
On Windows Firefox, Windows Edge, Windows Chrome,...?

**Comment by mmelko** [comment]
Everywhere. This is probably due to packaging the app by webpack. If I run docker images it works fine.

**Comment by thiagoelg** [comment]
Not exactly sure why, but this change seems to fix it for me on Windows:

```diff
diff --git a/src/App.tsx b/src/App.tsx
index f84f314..7a095e3 100644
--- a/src/App.tsx
+++ b/src/App.tsx
@@ -2,9 +2,9 @@ import './App.css';
 import { AlertProvider, MASLoading } from './components';
 import { AppLayout } from './layouts/AppLayout';
 import { AppRoutes } from './routes';
+import '@patternfly/react-core/dist/styles/base.css';
 import '@patternfly/patternfly/patternfly.css';
 import '@patternfly/patternfly/patternfly-theme-dark.css';
-import '@patternfly/react-core/dist/styles/base.css';
 import { Suspense } from 'react';
 import ReactDOM from 'react-dom';
 import { BrowserRouter as Router } from 'react-router-dom';
 ```
 
 
![image](https://user-images.githubusercontent.com/10515135/180301821-f4935bbe-22d0-4ad1-a6bb-118bf9d813ac.png)

I could open a PR if necessary :)

**Comment by Delawen** [comment]
The priority of stylesheets? Open a PR and see if it breaks in the tests

**Comment by mmelko** [comment]
Works now. Closing.
