### ISSUE TITLE
Ability to edit/create parameters for Kamelets

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#578]
**Describe the solution you'd like**
When users create Kamelets, they should be able to add new or delete/edit existing parameters. This would be suitable for a step extension that we could offer out of the box.

**Comment by mmelko** [comment]
so my understanding is to being able to create custom parameters from the UI and not the source code only. Is my assumption right? @kahboom @Delawen 

I can imagine to add new panel similar to step detail, but with "global" scope. There could be also dependencies and other things related to the flow for particular DSL. Is my assumption correct?

**Comment by kahboom** [comment]
>so my understanding is to being able to create custom parameters from the UI and not the source code only. Is my assumption right?

Yes that's correct @mmelko .

>I can imagine to add new panel similar to step detail, but with "global" scope. There could be also dependencies and other things related to the flow for particular DSL. Is my assumption correct?

So, no, this is what we spoke about yesterday. There is no need for a globally-scoped property yet. For this we use the Settings, and we don't have any requirement for defining dependencies from the UI yet. This issue is only specific to individual steps and being able to add parameters the same way you can do from the code editor, except from the Step Detail.

The other thing we discussed was that right now it will only be for KameletBindings, not Kamelets, because it seems to get erased if the parameter does not exist, and I'm not sure we will ever support that? For this we will have to discuss further with @Delawen , but it doesn't mean we can't already add in the feature for parameters specific to a custom KameletBinding.
