### ISSUE TITLE
Regression: Source code editor is resetting

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-ui#673]
**Describe the bug**
If you try to edit code in the code editor you get reset all the time. There is no way you can use the editor for code editing.

**To Reproduce**
See Video

**Expected behavior**
The editor should not auto-refresh from the UI model if you are working on the source code.

**Screenshots**
![editingCodeImpossible](https://user-images.githubusercontent.com/435853/188107450-c3ef2082-b571-4527-90a4-10df8eecfbed.gif)

**Comment by mmelko** [comment]
This was fixed by changes in code sync.
