### ISSUE TITLE
[UX] Provide help for configuration fields of steps

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-ui#674]
**Is your feature request related to a problem? Please describe.**
When opening the details view of a step you are able to configure it. The issue is that you are put in front of fields that have a rather very short name / description and often lack information, for instance "period" does not tell the user the measure of the period. Is it millis, seconds, hours, days? You have to leave the designer to search for the information elsewhere which is bad UX.

**Describe the solution you'd like**
We should provide a good description of the field and possibly also measures / formats either in a dedicated help area inside the same designer / form or we could also add a tooltip to either the field or a Help icon next to the field which contains that information. 

**Additional context**
![grafik](https://user-images.githubusercontent.com/435853/188116287-27515104-f8b4-4728-ab88-156bb4758791.png)

**Comment by Delawen** [comment]
All steps have a `description` field coming from the backend. Maybe add it as a helper `?` button?

**Comment by lhein** [comment]
Would be a solution...or as a tooltip.

**Comment by kahboom** [comment]
fixed with https://github.com/KaotoIO/kaoto-ui/pull/1018
