### ISSUE TITLE
`yarn start` sometimes complains about `dist/@mf-typescript/__types_index.json`

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#680]
**Describe the bug**
Getting the following error on `yarn start`:

```
Error saving the types index [Error: ENOENT: no such file or directory, open 'dist/@mf-typescript/__types_index.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'dist/@mf-typescript/__types_index.json'
}
```

The directory and file are created on that same build, but only after the check, so it fails. If I kill the process and restart it goes away.

**To Reproduce**
1. Run `rm -rf dist`
2. Run `yarn start`
3. See error

**Expected behavior**
The directory should be created automatically.

**Comment by kahboom** [comment]
Opened a PR here: https://github.com/module-federation/typescript/pull/11

**Comment by lordrip** [comment]
It seems that this is resolved, as a related pull request has been merged https://github.com/module-federation/typescript/pull/11#issuecomment-1236189828

**Comment by kahboom** [comment]
Thanks @lordrip !
