### ISSUE TITLE
Display a default icon if there is no icon for a given catalog item

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-ui#745]
See subject of the issue.

**Comment by kahboom** [comment]
@Delawen is this something we can instead do on the backend? I'd rather not mutate steps individually other than for `UUID`.

**Comment by Delawen** [comment]
I think @lhein means when the catalog from the backend is wrong, what to do on the frontend.

If some steps don't have an icon on the current backend that's an issue, but different from this one.

**Comment by lhein** [comment]
Haven't seen that for a while.

**Comment by kahboom** [comment]
Thanks Lars. Closing, we can reopen if it happens again.
