### ISSUE TITLE
add a layout direction preference to switch between horizontal and vertical layout of nodes

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-ui#767]
**Describe the solution you'd like**
It would be great if users could choose via a preference what type of layout direction (horizontal / vertical)  they want for the canvas.
The default for this preference should be vertical because it is easier to read and to scroll with more complex routes.

**Comment by kahboom** [comment]
Hey @lhein , this issue already exists here: #586  Feel free to add more details to it though.

**Comment by lhein** [comment]
Closing as duplicate of #586
