### ISSUE TITLE
[UX] when editing the integration name the field is not automatically focused

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-ui#768]
**Describe the bug**
When clicking the edit button next to the integration name I have to click again the name text field to finally be able to edit the name.

**To Reproduce**
1. open Kaoto
2. Click on the edito button next to the integration name
3. try to type the new name without clicking the text field again

**Expected behavior**
Clicking the edit button should automatically put the focus on the text field and maybe even autoselect the current name so it can be easily overwritten by just starting to type a new name.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/435853/194026660-e3dd8a2f-7b7f-409e-b414-61f18b5b0bff.png)

**Comment by kahboom** [comment]
I'd label this as an enhancement, not a bug.. I have the same opinion for #769 too but I digress ;D

**Comment by lhein** [comment]
I had the choice between feature request and bug :) Not really fitting in any of the 2.
