### ISSUE TITLE
Provide feedback selection on step

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#827]
### Please describe the feature that you want to propose

Currently, when a step is selected the config panel is opening. But there is not feedback selection so when moving between windows and getting back to it, it is hard to know to which step the config panel is corresponding.

**Comment by kahboom** [comment]
I was just thinking about this the other day actually, I agree. Maybe something to show which step is currently selected. I have some ideas for this. Thanks!
