### ISSUE TITLE
Provide feedback when deploy is not working

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#891]
### Please describe the feature that you want to propose

Currently tried only in V Code context but I suspect that in standalone mode we can have the same behavior, when clicking on "Deploy" button, there is a "running" image which is kept indefinitely when there is no active connection to any cluster.

It would be nice to provide an error message to guide user.

Current state:
![image](https://user-images.githubusercontent.com/1105127/199776079-150d7643-00f2-4f95-98cf-957edb579ae3.png)

**Comment by lordrip** [comment]
Closing it as duplicated of: https://github.com/KaotoIO/kaoto-ui/issues/2201
