### ISSUE TITLE
Publish a release of kaoto-ui usable by VS Code Kaoto

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-ui#894]
### Please describe the feature that you want to propose

kaoto-ui has been adapted to match multiplying architecture. A new release is required to be consumable by VS Code Kaoto and unblocked progress in this other project.

nota: the corresponding docker backend image is required

**Comment by apupier** [comment]
might be interesting to automate the release at this occasion https://github.com/KaotoIO/kaoto-ui/issues/859

**Comment by kahboom** [comment]
Done: https://www.npmjs.com/package/@kaoto/kaoto-ui

We should also consider to add any relevant members to the npm org for future releases: https://docs.npmjs.com/adding-members-to-your-organization
