### ISSUE TITLE
Code Editor: Update DSL in Settings automatically if doesn't match with DSL in code

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-ui#950]
## Background
We need to handle when the source code DSL doesn't match with the DSL in the Settings. For example, if the code has a DSL of Kamelet but in the Settings it's 'Camel Routes', it would return a blank page. This was partially fixed through the backend, but the frontend needs to handle this better.

Discussing with the team, we considered showing a warning to the user or automatically updating the Settings DSL, and decided on automatically updating the DSL in Settings to reflect the DSL from the code.

## Task
When the source code DSL doesn't match the DSL in Settings, automatically update the DSL in Settings, similarly to how we do for the Name property.

Relates to #787

**Comment by mmelko** [comment]
PR: #1200
